### PR TITLE
WIP: Add NuGet.Build.Tasks.Pack package

### PR DESCRIPTION
**Pull request by lukebakken**
This should re-enable per-PR releases to MyGet

### CODE REVIEW

**Comment by bording** [comment]
What problem are you running into? You should never need to reference this package directly.

**Comment by lukebakken** [comment]
Without it `dotnet pack` fails in our Linux CI build infrastructure. The repository with the CI code isn't public but this is the script that is run when a PR is built, for instance:

```
#!/bin/sh
set -ex

# redirect all output to standard output stream
exec 2>&1

readonly script_dir="$(cd "$(dirname "$0")" && pwd)"
readonly src_dir="$(cd "$script_dir/../../../rabbitmq_dotnet_client" && pwd)"
readonly assembly_info_file="$src_dir/projects/client/RabbitMQ.Client/src/client/properties/AssemblyInfo.cs"
readonly project_file="$src_dir/projects/client/RabbitMQ.Client/RabbitMQ.Client.csproj"

cd "$src_dir"

# make suffix from git sha
readonly suffix="pr-$(git log --pretty=format:'%h' -n 1)"

# perform main build
./build.sh

# build the client using the Release target
dotnet build "$src_dir/projects/client/RabbitMQ.Client" --configuration Release --version-suffix "$suffix"

# pack without re-building
dotnet pack "$src_dir/projects/client/RabbitMQ.Client" --no-build --configuration Release --version-suffix "$suffix"

# push the package to myget
dotnet nuget push -k "$MYGET_API_KEY" -s https://www.myget.org/F/rabbitmq/api/v2/package \
    "$src_dir/projects/client/RabbitMQ.Client/bin/Release/RabbitMQ.Client.*.nupkg"
```

**Comment by lukebakken** [comment]
Example failure output:

```
Time Elapsed 00:00:03.77
+ dotnet build /tmp/build/db7f1294/rabbitmq_dotnet_client/projects/client/RabbitMQ.Client --configuration Release --version-suffix 9a303203
Microsoft (R) Build Engine version 16.2.32702+c4012a063 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  Restore completed in 260.38 ms for /tmp/build/db7f1294/rabbitmq_dotnet_client/projects/client/RabbitMQ.Client/RabbitMQ.Client.csproj.
  RabbitMQ.Client -> /tmp/build/db7f1294/rabbitmq_dotnet_client/projects/client/RabbitMQ.Client/bin/Release/netstandard2.0/RabbitMQ.Client.dll
  RabbitMQ.Client -> /tmp/build/db7f1294/rabbitmq_dotnet_client/projects/client/RabbitMQ.Client/bin/Release/net461/RabbitMQ.Client.dll

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:02.10
+ dotnet pack /tmp/build/db7f1294/rabbitmq_dotnet_client/projects/client/RabbitMQ.Client --no-build --configuration Release --version-suffix 9a303203
Microsoft (R) Build Engine version 16.2.32702+c4012a063 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

/tmp/build/db7f1294/rabbitmq_dotnet_client/projects/client/RabbitMQ.Client/RabbitMQ.Client.csproj : error MSB4057: The target "pack" does not exist in the project.
```

**Comment by lukebakken** [comment]
Example success output:

```
+ dotnet build /tmp/build/db7f1294/rabbitmq_dotnet_client/projects/client/RabbitMQ.Client --configuration Release --version-suffix 07650ce2
Microsoft (R) Build Engine version 16.2.32702+c4012a063 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  Restore completed in 284.67 ms for /tmp/build/db7f1294/rabbitmq_dotnet_client/projects/client/RabbitMQ.Client/RabbitMQ.Client.csproj.
  RabbitMQ.Client -> /tmp/build/db7f1294/rabbitmq_dotnet_client/projects/client/RabbitMQ.Client/bin/Release/netstandard2.0/RabbitMQ.Client.dll
  RabbitMQ.Client -> /tmp/build/db7f1294/rabbitmq_dotnet_client/projects/client/RabbitMQ.Client/bin/Release/net461/RabbitMQ.Client.dll

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:02.25
+ dotnet pack /tmp/build/db7f1294/rabbitmq_dotnet_client/projects/client/RabbitMQ.Client --no-build --configuration Release --version-suffix 07650ce2
Microsoft (R) Build Engine version 16.2.32702+c4012a063 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  Successfully created package '/tmp/build/db7f1294/rabbitmq_dotnet_client/projects/client/RabbitMQ.Client/bin/Release/RabbitMQ.Client.6.0.0-07650ce2.nupkg'.
/root/.nuget/packages/nuget.build.tasks.pack/5.4.0/buildCrossTargeting/NuGet.Build.Tasks.Pack.targets(198,5): error NU5105: The package version '6.0.0-07650ce2' uses SemVer 2.0.0 or components of SemVer 1.0.0 that are not supported on legacy clients. Change the package version to a SemVer 1.0.0 string. If the version contains a release label it must start with a letter. This message can be ignored if the package is not intended for older clients. [/tmp/build/db7f1294/rabbitmq_dotnet_client/projects/client/RabbitMQ.Client/RabbitMQ.Client.csproj]
+ dotnet nuget push -k f9cd46b4-3c37-4774-a21e-ac55d00271ca -s https://www.myget.org/F/rabbitmq/api/v2/package /tmp/build/db7f1294/rabbitmq_dotnet_client/projects/client/RabbitMQ.Client/bin/Release/RabbitMQ.Client.*.nupkg
info : Pushing RabbitMQ.Client.6.0.0-07650ce2.nupkg to 'https://www.myget.org/F/rabbitmq/api/v2/package'...
info :   PUT https://www.myget.org/F/rabbitmq/api/v2/package/
info :   Created https://www.myget.org/F/rabbitmq/api/v2/package/ 1478ms
info : Your package was pushed.
```

Strangely enough that version is no longer showing up on myget.org. I could swear it was just there. Anyway, the goal of this process is to make pull request builds publicly accessible via NuGet.

**Comment by bording** [comment]
What version of the .NET Core SDK are those scripts running against? Something else must be going on, because that package is not needed to successfully pack a project.

The latest SDK is SDK 3.1.101, so I suggest installing that first and see if it works.

**Comment by lukebakken** [comment]
```
+ dotnet --version
2.2.402
```

I'll see about updating our CI image. I remember seeing this issue when testing on Windows until I installed the correct SDK version.

**Comment by michaelklishin** [comment]
I use 3.1 locally.

**Comment by lukebakken** [comment]
Yep I'm updating the CI image, which should resolve this.

**Comment by lukebakken** [comment]
@bording unfortunately installing both the 2.2 and 3.1 SDK packages on our debian build image does not resolve the issue. Please see the following output: [publish-pr-48-error.txt](https://github.com/rabbitmq/rabbitmq-dotnet-client/files/4125408/publish-pr-48-error.txt)

**Comment by bording** [comment]
I wish there was some way for me to repro the problem locally, because you 100% don't need to reference that package, so there is something else going on.

**Comment by lukebakken** [comment]
@bording I can provide a `Vagrantfile` that will provision a Debian 10 VM with exactly the same software that our CI image uses. Would that work for you?

Or, if you use Docker, the image we use is available [here](https://hub.docker.com/repository/docker/pivotalrabbitmq/ci-dotnet).

**Comment by bording** [comment]
I think I figured out the problem:

https://github.com/rabbitmq/rabbitmq-dotnet-client/blob/master/projects/client/RabbitMQ.Client/RabbitMQ.Client.csproj#L2-L4

You need to get rid of that.

**Comment by michaelklishin** [comment]
@bording's advice seems to work, at least without that dummy task `dotnet pack` succeeds for me.

**Comment by lukebakken** [comment]
Thanks @bording. I've got some other build errors to address before merging.

**Pull request closed without merging**
