### PR TITLE
Add API Approval test

### PR DESCRIPTION
**Pull request by bording**
## Proposed Changes

This adds an API approval test as suggested in #470. The idea behind this test is that the entire public API surface of the library will be written to the `APIApproval.Approve.approved.txt` file, and any time someone introduces a change to the public API surface, this test will fail if the file isn't updated. This ensures that any change is evaluated before the change is accepted.

When the test fails, a `APIApproval.Approve.received.txt` file will be written to disk, and it can be diffed. You can then rename it to `APIApproval.Approve.approved.txt` and the test will pass again.

## Types of Changes

What types of changes does your code introduce to this project?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes issue #NNNN)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation (correction or otherwise)
- [ ] Cosmetics (whitespace, appearance)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating
the PR. If you're unsure about any of them, don't hesitate to ask on the
mailing list. We're here to help! This is simply a reminder of what we are
going to look for before merging your code._

- [x] I have read the `CONTRIBUTING.md` document
- [x] I have signed the CA (see https://cla.pivotal.io/sign/rabbitmq)
- [x] All tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in related repositories

### CODE REVIEW

**Comment by michaelklishin** [comment]
Curiously test currently fails for me and the diff is 1126 lines strong. Something is off here. This is with .NET `2.1.403` on MacOS High Sierra.

**Comment by michaelklishin** [comment]
The top of the files is identical:

```
[assembly: System.Runtime.CompilerServices.InternalsVisibleToAttribute("Unit")]
namespace RabbitMQ.Client
{
    public class AmqpTcpEndpoint
    {
        public const int DefaultAmqpSslPort = 5671;
        public const int UseDefaultPort = -1;
        public AmqpTcpEndpoint(string hostName, int portOrMinusOne, RabbitMQ.Client.SslOption ssl) { }
        public AmqpTcpEndpoint(string hostName, int portOrMinusOne = -1) { }
        public AmqpTcpEndpoint() { }
        public AmqpTcpEndpoint(System.Uri uri, RabbitMQ.Client.SslOption ssl) { }
        public AmqpTcpEndpoint(System.Uri uri) { }
        public System.Net.Sockets.AddressFamily AddressFamily { get; set; }
        public string HostName { get; set; }
        public int Port { get; set; }
        public RabbitMQ.Client.IProtocol Protocol { get; }
        public RabbitMQ.Client.SslOption Ssl { get; set; }
        public object Clone() { }
        public RabbitMQ.Client.AmqpTcpEndpoint CloneWithHostname(string hostname) { }
        public override bool Equals(object obj) { }
        public override int GetHashCode() { }
        public static RabbitMQ.Client.AmqpTcpEndpoint Parse(string address) { }
        public static RabbitMQ.Client.AmqpTcpEndpoint[] ParseMultiple(string addresses) { }
        public override string ToString() { }
    }
    public struct AmqpTimestamp
    {
        public AmqpTimestamp(long unixTime) { }
        public long UnixTime { get; }
        public override string ToString() { }
    }
    public class AmqpVersion
    {
        public AmqpVersion(int major, int minor) { }
        public int Major { get; }
        public int Minor { get; }
        public override bool Equals(object other) { }
        public override int GetHashCode() { }
        public override string ToString() { }
    }

// [snip]
```

It doesn't seem to be that the difference is in line endings as I first thought.

**Comment by bording** [comment]
@michaelklishin So are you seeing actual differences in the two files?

**Comment by michaelklishin** [comment]
@bording [here](https://gist.github.com/michaelklishin/6b863c0e49c0e1bc701e781a678c243a) is the diff.

**Comment by michaelklishin** [comment]
I tried a clean build and the outcome is the same.

**Comment by bording** [comment]
@michaelklishin That's not really helping. Can you email me the `received` file that is created when you run the test?

**Comment by michaelklishin** [comment]
Sent.

**Comment by bording** [comment]
@michaelklishin Thanks that helped me realize what the problem was. I had an outdated `autogenerated-api-0-9-1.cs` on my machine, so the original approval file had stuff in there that wasn't supposed to be in there.

If you try the test now, I suspect it will work.

I'm now wondering if there would be a way to prevent that scenario from happening, perhaps by being able to have the file be regenerated automatically if it needs to be or something. Alternatively, that file could actually just be checked in as part of the repo, and updated as needed.

**Comment by michaelklishin** [comment]
The tests pass now. @kjnilsson any objections to adopting this API test?

**Comment by kjnilsson** [comment]
I have no objections. However ci fails with:

```ApprovalTests.Core.Exceptions.ApprovalMismatchException : Failed Approval: Received file /tmp/build/b95f7b06/rabbitmq_dotnet_client/projects/client/Unit/src/unit/APIApproval.Approve.received.txt does not match approved file /tmp/build/b95f7b06/rabbitmq_dotnet_client/projects/client/Unit/src/unit/APIApproval.Approve.approved.txt```

**Comment by bording** [comment]
@kjnilsson Can you make the two files available so we can see what is different between them?

**Comment by kjnilsson** [comment]
@bording having some trouble copying the files (computers eh?) but managed to get a diff:

```
166,169d165
<     public class static EndpointResolverExtensions
<     {
<         public static T SelectOne<T>(this RabbitMQ.Client.IEndpointResolver resolver, System.Func<RabbitMQ.Client.AmqpTcpEndpoint, T> selector) { }
<     }
178a175,178
>     public class static EndpointResolverExtensions
>     {
>         public static T SelectOne<T>(this RabbitMQ.Client.IEndpointResolver resolver, System.Func<RabbitMQ.Client.AmqpTcpEndpoint, T> selector) { }
>     }
530,534d529
<     public class static Protocols
<     {
<         public static RabbitMQ.Client.IProtocol AMQP_0_9_1 { get; }
<         public static RabbitMQ.Client.IProtocol DefaultProtocol { get; }
<     }
540a536,540
>     public class static Protocols
>     {
>         public static RabbitMQ.Client.IProtocol AMQP_0_9_1 { get; }
>         public static RabbitMQ.Client.IProtocol DefaultProtocol { get; }
>     }
593,594d592
<         public System.Net.Security.LocalCertificateSelectionCallback CertificateSelectionCallback { get; set; }
<         public System.Net.Security.RemoteCertificateValidationCallback CertificateValidationCallback { get; set; }
596a595,596
>         public System.Net.Security.LocalCertificateSelectionCallback CertificateSelectionCallback { get; set; }
>         public System.Net.Security.RemoteCertificateValidationCallback CertificateValidationCallback { get; set; }
868d867
<         protected System.Collections.Generic.IDictionary<string, object> m_table;
869a869
>         protected System.Collections.Generic.IDictionary<string, object> m_table;
1812a1813,1835
>         void ConnectionTuneOk(ushort channelMax, uint frameMax, ushort heartbeat);
>         void HandleBasicAck(ulong deliveryTag, bool multiple);
>         void HandleBasicCancel(string consumerTag, bool nowait);
>         void HandleBasicCancelOk(string consumerTag);
>         void HandleBasicConsumeOk(string consumerTag);
>         void HandleBasicDeliver(string consumerTag, ulong deliveryTag, bool redelivered, string exchange, string routingKey, [RabbitMQ.Client.Apigen.Attributes.AmqpContentHeaderMappingAttribute()] RabbitMQ.Client.IBasicProperties basicProperties, [RabbitMQ.Client.Apigen.Attributes.AmqpContentBodyMappingAttribute()] byte[] body);
>         void HandleBasicGetEmpty();
>         void HandleBasicGetOk(ulong deliveryTag, bool redelivered, string exchange, string routingKey, uint messageCount, [RabbitMQ.Client.Apigen.Attributes.AmqpContentHeaderMappingAttribute()] RabbitMQ.Client.IBasicProperties basicProperties, [RabbitMQ.Client.Apigen.Attributes.AmqpContentBodyMappingAttribute()] byte[] body);
>         void HandleBasicNack(ulong deliveryTag, bool multiple, bool requeue);
>         void HandleBasicRecoverOk();
>         void HandleBasicReturn(ushort replyCode, string replyText, string exchange, string routingKey, [RabbitMQ.Client.Apigen.Attributes.AmqpContentHeaderMappingAttribute()] RabbitMQ.Client.IBasicProperties basicProperties, [RabbitMQ.Client.Apigen.Attributes.AmqpContentBodyMappingAttribute()] byte[] body);
>         void HandleChannelClose(ushort replyCode, string replyText, ushort classId, ushort methodId);
>         void HandleChannelCloseOk();
>         void HandleChannelFlow(bool active);
>         [RabbitMQ.Client.Apigen.Attributes.AmqpMethodMappingAttribute(null, "connection", "blocked")]
>         void HandleConnectionBlocked(string reason);
>         void HandleConnectionClose(ushort replyCode, string replyText, ushort classId, ushort methodId);
>         void HandleConnectionOpenOk([RabbitMQ.Client.Apigen.Attributes.AmqpFieldMappingAttribute("RabbitMQ.Client.Framing", "reserved1")] string knownHosts);
>         void HandleConnectionSecure(byte[] challenge);
>         void HandleConnectionStart(byte versionMajor, byte versionMinor, System.Collections.Generic.IDictionary<string, object> serverProperties, byte[] mechanisms, byte[] locales);
>         void HandleConnectionTune(ushort channelMax, uint frameMax, ushort heartbeat);
>         void HandleConnectionUnblocked();
>         void HandleQueueDeclareOk(string queue, uint messageCount, uint consumerCount);
1870,1897d1892
<         void ConnectionTuneOk(ushort channelMax, uint frameMax, ushort heartbeat);
<         void HandleBasicAck(ulong deliveryTag, bool multiple);
<         void HandleBasicCancel(string consumerTag, bool nowait);
<         void HandleBasicCancelOk(string consumerTag);
<         void HandleBasicConsumeOk(string consumerTag);
<         void HandleBasicDeliver(string consumerTag, ulong deliveryTag, bool redelivered, string exchange, string routingKey, [RabbitMQ.Client.Apigen.Attributes.AmqpContentHeaderMappingAttribute()] RabbitMQ.Client.IBasicProperties basicProperties, [RabbitMQ.Client.Apigen.Attributes.AmqpContentBodyMappingAttribute()] byte[] body);
<         void HandleBasicGetEmpty();
<         void HandleBasicGetOk(ulong deliveryTag, bool redelivered, string exchange, string routingKey, uint messageCount, [RabbitMQ.Client.Apigen.Attributes.AmqpContentHeaderMappingAttribute()] RabbitMQ.Client.IBasicProperties basicProperties, [RabbitMQ.Client.Apigen.Attributes.AmqpContentBodyMappingAttribute()] byte[] body);
<         void HandleBasicNack(ulong deliveryTag, bool multiple, bool requeue);
<         void HandleBasicRecoverOk();
<         void HandleBasicReturn(ushort replyCode, string replyText, string exchange, string routingKey, [RabbitMQ.Client.Apigen.Attributes.AmqpContentHeaderMappingAttribute()] RabbitMQ.Client.IBasicProperties basicProperties, [RabbitMQ.Client.Apigen.Attributes.AmqpContentBodyMappingAttribute()] byte[] body);
<         void HandleChannelClose(ushort replyCode, string replyText, ushort classId, ushort methodId);
<         void HandleChannelCloseOk();
<         void HandleChannelFlow(bool active);
<         [RabbitMQ.Client.Apigen.Attributes.AmqpMethodMappingAttribute(null, "connection", "blocked")]
<         void HandleConnectionBlocked(string reason);
<         void HandleConnectionClose(ushort replyCode, string replyText, ushort classId, ushort methodId);
<         void HandleConnectionOpenOk([RabbitMQ.Client.Apigen.Attributes.AmqpFieldMappingAttribute("RabbitMQ.Client.Framing", "reserved1")] string knownHosts);
<         void HandleConnectionSecure(byte[] challenge);
<         void HandleConnectionStart(byte versionMajor, byte versionMinor, System.Collections.Generic.IDictionary<string, object> serverProperties, byte[] mechanisms, byte[] locales);
<         void HandleConnectionTune(ushort channelMax, uint frameMax, ushort heartbeat);
<         void HandleConnectionUnblocked();
<         void HandleQueueDeclareOk(string queue, uint messageCount, uint consumerCount);
<     }
<     public class InboundFrame : RabbitMQ.Client.Impl.Frame
<     {
<         public RabbitMQ.Util.NetworkBinaryReader GetReader() { }
<         public static RabbitMQ.Client.Impl.InboundFrame ReadFrom(RabbitMQ.Util.NetworkBinaryReader reader) { }
1918a1914,1918
>     public class InboundFrame : RabbitMQ.Client.Impl.Frame
>     {
>         public RabbitMQ.Util.NetworkBinaryReader GetReader() { }
>         public static RabbitMQ.Client.Impl.InboundFrame ReadFrom(RabbitMQ.Util.NetworkBinaryReader reader) { }
>     }
1980c1980
<     public abstract class ModelBase : RabbitMQ.Client.IModel, RabbitMQ.Client.Impl.IFullModel, RabbitMQ.Client.IRecoverable, System.IDisposable
---
>     public abstract class ModelBase : RabbitMQ.Client.IModel, RabbitMQ.Client.IRecoverable, RabbitMQ.Client.Impl.IFullModel, System.IDisposable
2004,2026d2003
<         public abstract void _Private_BasicCancel(string consumerTag, bool nowait);
<         public abstract void _Private_BasicConsume(string queue, string consumerTag, bool noLocal, bool autoAck, bool exclusive, bool nowait, System.Collections.Generic.IDictionary<string, object> arguments);
<         public abstract void _Private_BasicGet(string queue, bool autoAck);
<         public abstract void _Private_BasicPublish(string exchange, string routingKey, bool mandatory, RabbitMQ.Client.IBasicProperties basicProperties, byte[] body);
<         public abstract void _Private_BasicRecover(bool requeue);
<         public abstract void _Private_ChannelClose(ushort replyCode, string replyText, ushort classId, ushort methodId);
<         public abstract void _Private_ChannelCloseOk();
<         public abstract void _Private_ChannelFlowOk(bool active);
<         public abstract void _Private_ChannelOpen(string outOfBand);
<         public abstract void _Private_ConfirmSelect(bool nowait);
<         public abstract void _Private_ConnectionClose(ushort replyCode, string replyText, ushort classId, ushort methodId);
<         public abstract void _Private_ConnectionCloseOk();
<         public abstract void _Private_ConnectionOpen(string virtualHost, string capabilities, bool insist);
<         public abstract void _Private_ConnectionSecureOk(byte[] response);
<         public abstract void _Private_ConnectionStartOk(System.Collections.Generic.IDictionary<string, object> clientProperties, string mechanism, byte[] response, string locale);
<         public abstract void _Private_ExchangeBind(string destination, string source, string routingKey, bool nowait, System.Collections.Generic.IDictionary<string, object> arguments);
<         public abstract void _Private_ExchangeDeclare(string exchange, string type, bool passive, bool durable, bool autoDelete, bool @internal, bool nowait, System.Collections.Generic.IDictionary<string, object> arguments);
<         public abstract void _Private_ExchangeDelete(string exchange, bool ifUnused, bool nowait);
<         public abstract void _Private_ExchangeUnbind(string destination, string source, string routingKey, bool nowait, System.Collections.Generic.IDictionary<string, object> arguments);
<         public abstract void _Private_QueueBind(string queue, string exchange, string routingKey, bool nowait, System.Collections.Generic.IDictionary<string, object> arguments);
<         public abstract void _Private_QueueDeclare(string queue, bool passive, bool durable, bool exclusive, bool autoDelete, bool nowait, System.Collections.Generic.IDictionary<string, object> arguments);
<         public abstract uint _Private_QueueDelete(string queue, bool ifUnused, bool ifEmpty, bool nowait);
<         public abstract uint _Private_QueuePurge(string queue, bool nowait);
2065d2041
<         protected virtual void handleAckNack(ulong deliveryTag, bool multiple, bool isNack) { }
2119a2096,2119
>         public abstract void _Private_BasicCancel(string consumerTag, bool nowait);
>         public abstract void _Private_BasicConsume(string queue, string consumerTag, bool noLocal, bool autoAck, bool exclusive, bool nowait, System.Collections.Generic.IDictionary<string, object> arguments);
>         public abstract void _Private_BasicGet(string queue, bool autoAck);
>         public abstract void _Private_BasicPublish(string exchange, string routingKey, bool mandatory, RabbitMQ.Client.IBasicProperties basicProperties, byte[] body);
>         public abstract void _Private_BasicRecover(bool requeue);
>         public abstract void _Private_ChannelClose(ushort replyCode, string replyText, ushort classId, ushort methodId);
>         public abstract void _Private_ChannelCloseOk();
>         public abstract void _Private_ChannelFlowOk(bool active);
>         public abstract void _Private_ChannelOpen(string outOfBand);
>         public abstract void _Private_ConfirmSelect(bool nowait);
>         public abstract void _Private_ConnectionClose(ushort replyCode, string replyText, ushort classId, ushort methodId);
>         public abstract void _Private_ConnectionCloseOk();
>         public abstract void _Private_ConnectionOpen(string virtualHost, string capabilities, bool insist);
>         public abstract void _Private_ConnectionSecureOk(byte[] response);
>         public abstract void _Private_ConnectionStartOk(System.Collections.Generic.IDictionary<string, object> clientProperties, string mechanism, byte[] response, string locale);
>         public abstract void _Private_ExchangeBind(string destination, string source, string routingKey, bool nowait, System.Collections.Generic.IDictionary<string, object> arguments);
>         public abstract void _Private_ExchangeDeclare(string exchange, string type, bool passive, bool durable, bool autoDelete, bool @internal, bool nowait, System.Collections.Generic.IDictionary<string, object> arguments);
>         public abstract void _Private_ExchangeDelete(string exchange, bool ifUnused, bool nowait);
>         public abstract void _Private_ExchangeUnbind(string destination, string source, string routingKey, bool nowait, System.Collections.Generic.IDictionary<string, object> arguments);
>         public abstract void _Private_QueueBind(string queue, string exchange, string routingKey, bool nowait, System.Collections.Generic.IDictionary<string, object> arguments);
>         public abstract void _Private_QueueDeclare(string queue, bool passive, bool durable, bool exclusive, bool autoDelete, bool nowait, System.Collections.Generic.IDictionary<string, object> arguments);
>         public abstract uint _Private_QueueDelete(string queue, bool ifUnused, bool ifEmpty, bool nowait);
>         public abstract uint _Private_QueuePurge(string queue, bool nowait);
>         protected virtual void handleAckNack(ulong deliveryTag, bool multiple, bool isNack) { }
2455d2454
<         public static int validatedTimeout(int timeout) { }
2458a2458
>         public static int validatedTimeout(int timeout) { }
2466a2467,2471
>     public enum EitherAlternative
>     {
>         Left = 0,
>         Right = 1,
>     }
2475,2479d2479
<     public enum EitherAlternative
<     {
<         Left = 0,
<         Right = 1,
<     }
2538a2539,2543
>     public struct SharedQueueEnumerator<T> : System.Collections.Generic.IEnumerator<T>, System.Collections.IEnumerator, System.IDisposable
>     {
>         public SharedQueueEnumerator(RabbitMQ.Util.SharedQueue<T> queue) { }
>         public void Dispose() { }
>     }
2549,2553d2553
<     }
<     public struct SharedQueueEnumerator<T> : System.Collections.Generic.IEnumerator<T>, System.Collections.IEnumerator, System.IDisposable
<     {
<         public SharedQueueEnumerator(RabbitMQ.Util.SharedQueue<T> queue) { }
<         public void Dispose() { }

```

**Comment by bording** [comment]
To be honest, I can't really get anything meaningful out of that.

**Comment by kjnilsson** [comment]
The only actual difference I can see is that the order of the ModelBase interfaces is different:

```<     public abstract class ModelBase : RabbitMQ.Client.IModel, RabbitMQ.Client.Impl.IFullModel, RabbitMQ.Client.IRecoverable, System.IDisposable
---
>     public abstract class ModelBase : RabbitMQ.Client.IModel, RabbitMQ.Client.IRecoverable, RabbitMQ.Client.Impl.IFullModel, System.IDisposable```

**Comment by bording** [comment]
@kjnilsson That is strange! I'll see if I can figure out why that would be different.

**Comment by michaelklishin** [comment]
@bording perhaps there's iteration over a map/dictionary somewhere?

**Comment by michaelklishin** [comment]
@bording have you had a chance to take a look at finishing this? (no pressure)

**Comment by bording** [comment]
@michaelklishin It's still on my todo list, but I haven't been able to get back to it yet. The next step I want to take is to get the tests running locally under linux to see if I can repro the problem myself.

**Comment by bording** [comment]
Finally had some time to look at this more. Turns out that `PublicApiGenerator` was relying on the default string comparer for sorting, and that will result in difference results between Windows and Linux.

I'm going to submit a PR for `PublicApiGenerator` to switch to ordinal comparison, but in the mean time I've just copied the code and made the changes directly. Seeing out how the NuGet package is a source package already, this seemed like a decent way to handle it for now.

I think it would be okay to merge this now, and when there's an updated version of `PublicApiGenerator`, we can switch back to using it.

**Comment by michaelklishin** [comment]
@bording oh, good catch, thank you!

**Comment by kjnilsson** [comment]
Weirdly this passed the PR build but fails the main ci build after merge. Will investigate.

**Comment by bording** [comment]
> Weirdly this passed the PR build but fails the main ci build after merge. Will investigate.

@kjnilsson Let me know how I can help. Seeing both the approved and received files should help figure out what's happening.

**Pull request merged**
