### PR TITLE
BasicGetResult should get a copy of HandleBasicGetOk's body

### LINKED ISSUE #994: BasicGetResult body memory safety in 6.x+
Hi,

It looks I've accidentally found an amusing bug. Let me start from this example(by the way, I'm using v6.2.1):

```
using System;
using System.Collections.Generic;
using System.Threading;
using RabbitMQ.Client;


namespace DotNetExperiments
{
    public static class Program
    {
        private static readonly ReadOnlyMemory<byte> SentBody = new byte[] {42, 42, 42, 42, 42};
        
        public static void Main()
        {
            // Boostrap stuff
            var connectionFactory = new ConnectionFactory
            {
                Uri = new Uri("amqps://apwlvbny:ZPrB0qqbBkBE0jOwUAHERRXL39fog2jc@rattlesnake.rmq.cloudamqp.com/apwlvbny")
            };
            var connection = connectionFactory.CreateConnection();
            var model = connection.CreateModel();
            var queue = Guid.NewGuid().ToString("N");
            model.QueueDeclare(queue, false, false);

            // Let's store all received bodies
            var receivedBodies = new List<ReadOnlyMemory<byte>>();
            while (true)
            {
                Thread.Sleep(100);

                // Then every iteration we recheck all received bodies: they should match with sentBody 
                foreach (var receivedBody in receivedBodies) CheckReceivedBody(receivedBody);

                model.BasicPublish("", queue, true, null, SentBody);
                var getResult = model.BasicGet(queue, true);
                if (getResult == null)
                    continue;

                // Store received body
                receivedBodies.Add(getResult.Body);
            }
        }

        private static void CheckReceivedBody(ReadOnlyMemory<byte> receivedBody)
        {
            if (receivedBody.Span.SequenceEqual(SentBody.Span))
                return;
            
            Console.WriteLine($"Mismatch: {string.Join(",", receivedBody.Span.ToArray())} != {string.Join(",", SentBody.Span.ToArray())}");
        }
    }
}
```

After a couple of seconds mismatches have been found:
```
Mismatch: 8,0,0,0,0 != 42,42,42,42,42
Mismatch: 8,0,0,0,0 != 42,42,42,42,42
Mismatch: 8,0,0,0,0 != 42,42,42,42,42
Mismatch: 8,0,0,0,0 != 42,42,42,42,42
Mismatch: 8,0,0,0,0 != 42,42,42,42,42
Mismatch: 8,0,0,0,0 != 42,42,42,42,42
Mismatch: 8,0,0,0,0 != 42,42,42,42,42
Mismatch: 8,0,0,0,0 != 42,42,42,42,42
Mismatch: 8,0,0,0,0 != 42,42,42,42,42
Mismatch: 8,0,0,0,0 != 42,42,42,42,42
Mismatch: 8,0,0,0,0 != 42,42,42,42,42
```

An array under `BasicGetResult.Body` was reused. 

The reason of it might be the following: after a [completion](https://github.com/rabbitmq/rabbitmq-dotnet-client/blob/6.x/projects/RabbitMQ.Client/client/impl/ModelBase.cs#L721) of BasicGet RPC continuation, a command is [disposed](https://github.com/rabbitmq/rabbitmq-dotnet-client/blob/6.x/projects/RabbitMQ.Client/client/impl/Session.cs#L52) and an array under `BasicGetResult.Body` is returned to `ArrayPool`. This makes usage of `BasicGetResult.Body` unpredictable at least(https://github.com/EasyNetQ/EasyNetQ/issues/1153) because it is unsafe to use `BasicGetResult.Body` right after `model.BasicGet` returns it.

It looks like the only fix is to copy a body a [bit before](https://github.com/rabbitmq/rabbitmq-dotnet-client/blob/6.x/projects/RabbitMQ.Client/client/impl/ModelBase.cs#L728) a completion of a continuation.

Could you please confirm the issue?

### PR DESCRIPTION
**Pull request by Pliner**
## Proposed Changes

Fixes #994 

## Types of Changes

What types of changes does your code introduce to this project?
_Put an `x` in the boxes that apply_

- [X] Bug fix (non-breaking change which fixes issue #NNNN)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause an observable behavior change in existing systems)
- [ ] Documentation improvements (corrections, new content, etc)
- [ ] Cosmetic change (whitespace, formatting, etc)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating
the PR. If you're unsure about any of them, don't hesitate to ask on the
mailing list. We're here to help! This is simply a reminder of what we are
going to look for before merging your code._

- [X] I have read the `CONTRIBUTING.md` document
- [X] I have signed the CA (see https://cla.pivotal.io/sign/rabbitmq)
- [ ] All tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in related repositories

### CODE REVIEW

**Review by michaelklishin — APPROVED** [review]
Accepting per discussion in #994.

**Comment by michaelklishin** [comment]
Thank you for contributing!

**Comment by Pliner** [comment]
@michaelklishin Do you mind to release it as 6.2.2? It will save rare users of this method from mysterious bugs  🙄

**Comment by HenryGarle** [comment]
I assume this is being held up by the 6.2.2 release? This issue caused me a real headache and the work around for it slows everything to a crawl if you are running multiple queues as you have to lock every get request.

**Comment by aleksanderzubkov** [comment]
Please release 6.2.2. We need this fix. We are using Rabbit to stream data to Clickhouse and have this bug on high load.

**Comment by VladSnap** [comment]
I wasted a lot of time because of this. Did a lot of tests to understand the problem.
Please release a fix.

**Comment by michaelklishin** [comment]
We will try to put out a `6.2.x` release in the next couple of days.

**Comment by HenryGarle** [comment]
> We will try to put out a `6.2.x` release in the next couple of days.

Any news on this now? Its a real problem and getting to be a bit silly. I'd rather not have to pull down and build a custom version but at this point there is not really another option.

**Comment by michaelklishin** [comment]
The news is that I'm on PTO. The .NET client pipeline is currently red for reasons that have nothing to do with the actual client or its test suite (as far as I can tell). It may take some time to resolve.

**Comment by michaelklishin** [comment]
Tests now pass, and the publishing task has succeeded but I don't see `6.2.2` up on nuget.org yet. Maybe it takes a bit of time to be indexed.

**Comment by michaelklishin** [comment]
The published version ended up being an alpha one. I will remove it.

After tagging `v6.2.2` and republishing the version seems to be `6.2.2`. It takes a few minutes for nuget.org to begin listing it.

**Comment by michaelklishin** [comment]
[`6.2.2` is up on nuget.org](https://www.nuget.org/packages/RabbitMQ.Client/6.2.2).

**Comment by Pliner** [comment]
> [`6.2.2` is up on nuget.org](https://www.nuget.org/packages/RabbitMQ.Client/6.2.2).

Thanks!

**Comment by HenryGarle** [comment]
> [`6.2.2` is up on nuget.org](https://www.nuget.org/packages/RabbitMQ.Client/6.2.2).

Awesome, thank you very much!

**Pull request merged**
