### PR TITLE
Migrate to VS 2019 (mostly cosmetic)

### PR DESCRIPTION
**Pull request by lukebakken**
@bording the update to 2019 was pretty painless.

### CODE REVIEW

**Comment by bording** [comment]
@lukebakken Almost all of this PR is noise that should be reverted, for example all the project files should be reverted.

**Comment by lukebakken** [comment]
@bording the test file didn't have a namespace, so I added one. I'll simplify the rest of the changes - they were all "automagical" when I opened the solution in VS 2019.

**Comment by bording** [comment]
@lukebakken I see you force pushed some changes, but there are still things in the project files that shouldn't be in there.

The only thing that could/should be changed there is the removal of `LangVersion`.

**Comment by lukebakken** [comment]
Really, so this is problematic?

```
ToolsVersion="Current"
```

Why would it be added during an upgrade then?

**Comment by bording** [comment]
It's not that it's problematic, it's that its completely unnecessary noise.

> Why would it be added during an upgrade then?

Because parts of Visual Studio still don't fully understand the new SDK-style projects, so they add a bunch of junk that isn't needed.

**Comment by lukebakken** [comment]
Alrighty then, so this will be a PR to remove some whitespace and add a namespace to some tests 😄

**Comment by bording** [comment]
> Alrighty then, so this will be a PR to remove some whitespace and add a namespace to some tests 😄

I actually find the whitespace in the project files to be beneficial, makes them more readable. For my projects, I space things out intentionally.

Completely up to you though.

**Pull request merged**
