### PR TITLE
Fixing header parsing bug

### PR DESCRIPTION
**Pull request by stebet**
## Proposed Changes

Headers are not currently parsed correctly, and I'm not sure how long it has been broken. I've added a test that passes now to make sure this doesn't break again.

## Types of Changes

- [X] Bug fix (non-breaking change which fixes issue #NNNN)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause an observable behavior change in existing systems)
- [ ] Documentation improvements (corrections, new content, etc)
- [ ] Cosmetic change (whitespace, formatting, etc)

## Checklist

- [X] I have read the `CONTRIBUTING.md` document
- [X] I have signed the CA (see https://cla.pivotal.io/sign/rabbitmq)
- [X] All tests pass locally with my changes
- [X] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in related repositories

## Further Comments

### CODE REVIEW

**Review by michaelklishin — DISMISSED** [review]

**Comment by stebet** [comment]
Mind giving this another review @michaelklishin. I fixed a linting error.

**Comment by michaelklishin** [comment]
Thank you! This definitely needs backporting.

**Comment by bollhals** [comment]
This was introduced by #1096 which did not target 6.x, so I don't think we need to backport it.

**Comment by stebet** [comment]
> This was introduced by #1096 which did not target 6.x, so I don't think we need to backport it.

Yep, see here: https://github.com/rabbitmq/rabbitmq-dotnet-client/pull/1096/files#r994516089. Sneaky bug, all due to one missing `.Slice`

**Pull request merged**
