### PR TITLE
DRAFT Heartbeat reader and writer in dedicated threads

### PR DESCRIPTION
**Pull request by RKikuchi**
## Proposed Changes

Wrapping heartbeat timers in dedicated native threads to avoid missing heartbeats due to ThreadPool starvation.

## Types of Changes

What types of changes does your code introduce to this project?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes issue #NNNN)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation (correction or otherwise)
- [ ] Cosmetics (whitespace, appearance)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating
the PR. If you're unsure about any of them, don't hesitate to ask on the
mailing list. We're here to help! This is simply a reminder of what we are
going to look for before merging your code._

- [ ] I have read the `CONTRIBUTING.md` document
- [x] I have signed the CA (see https://cla.pivotal.io/sign/rabbitmq)
- [ ] All tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in related repositories

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@RKikuchi Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/rabbitmq?repositoryId=rabbitmq/rabbitmq-dotnet-client&pullRequestId=520)!

[Click here](https://cla.pivotal.io/sync/rabbitmq?repositoryId=rabbitmq/rabbitmq-dotnet-client&pullRequestId=520) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@RKikuchi Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/rabbitmq?repositoryId=rabbitmq/rabbitmq-dotnet-client&pullRequestId=520)!

**Comment by michaelklishin** [comment]
Thank you but I believe we have been there before (possibly in a different client, though) and some users raised a complaint about how many threads and timers are used per connection. So this is not a no-brainer.

@kjnilsson @lukebakken @bording thoughts?

#71 and #84 are somewhat relevant.

**Comment by bording** [comment]
@RKikuchi What scenario did you run into where you found the heartbeats impacted by thread pool starvation?

Thread pool starvation doesn't just happen, but is a symptom of some other bad behavior going on, for example someone doing something in async code that causes the thread to block instead of properly awaiting.

That being said, it doesn't seem unreasonable to protect the heartbeat mechanism from starvation by having dedicated threads for them. If they are spending most of their time sleeping anyway, I don't really see a problem with there being more threads hanging around.

Currently, this PR is only using the custom timer class for the .NET Framework target, but that doesn't really make sense. It should be cleaned up to be used for all targets, so there's no need for all the conditional compilation going on.

**Comment by michaelklishin** [comment]
Closing due to inactivity and now conflicts. Please resubmit if you have a more complete justification for this change.

**Pull request closed without merging**
