### PR TITLE
Enable deterministic builds

### LINKED ISSUE #805: Enable Deterministic Builds for packaged releases
[Deterministic builds](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-options/deterministic-compiler-option) should be enabled for NuGet releases to both enable source linking and to verify that the code has indded been built with the referenced sources.

There is an excellent guide on how to enable this by @clairernovotny here: https://github.com/clairernovotny/DeterministicBuilds

### PR DESCRIPTION
**Pull request by lukebakken**
Fixes #805

Note: does not seem to work just yet

### CODE REVIEW

**Comment by lukebakken** [comment]
@stebet this doesn't seem to work just yet. I have tested by running these commands in my local clone while on this branch:

```
git clean -fxd
$env:CONCOURSE_CI_BUILD='true'
.\build.bat
```

As you can see, the build is not deterministic. I'm using SDK 3.1.201.

image

**Comment by stebet** [comment]
I'll take a quick look tomorrow :)

**Comment by bording** [comment]
@lukebakken I just pushed up a change that should fix it. The workaround mentioned on https://github.com/clairernovotny/DeterministicBuilds is required for now to get it working.

**Comment by lukebakken** [comment]
Thanks @bording I hadn't yet tried that and was hoping it wasn't necessary.

**Comment by bording** [comment]
> Thanks @bording I hadn't yet tried that and was hoping it wasn't necessary.

Yeah unfortunately it is for now. From my understanding of the issue, those files aren't located inside the repository by default, so paths to them won't get the Deterministic treatment, which results in it failing.

**Comment by lukebakken** [comment]
Thanks again @bording , verified via this package:

https://www.myget.org/feed/rabbitmq/package/nuget/RabbitMQ.Client/6.0.0-rc.3.6-pr.809

**Pull request merged**
