### PR TITLE
use async consumer only

### PR DESCRIPTION
**Pull request by bollhals**
## Proposed Changes

Gets rid of the duality of AsyncDefaultConsumer and DefaultConsumer. 

## Types of Changes

- [ ] Bug fix (non-breaking change which fixes issue #NNNN)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause an observable behavior change in existing systems)
- [ ] Documentation improvements (corrections, new content, etc)
- [ ] Cosmetic change (whitespace, formatting, etc)

## Checklist

- [x] I have read the `CONTRIBUTING.md` document
- [x] I have signed the CA (see https://cla.pivotal.io/sign/rabbitmq)
- [x] All tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in related repositories

## Further Comments

There's still a bit more work, but opening this PR now due to https://github.com/rabbitmq/rabbitmq-dotnet-client/issues/1413#issuecomment-2243859512

### CODE REVIEW

**Comment by bollhals** [comment]
What's the preference for the resulting name of the consumer. Should it be e.g. IBasicConsumer or IAsyncBasicConsumer?

**Comment by lukebakken** [comment]
Please use `IAsyncBasicConsumer`, thanks.

**Comment by bollhals** [comment]
> Please use `IAsyncBasicConsumer`, thanks.

Just to make sure we understood each other: I'm for sure use the api of the IAsyncBasicConsumer, but should the name itself be IAsyncBasicConsumer or do you want to remove the Async part, as there's only one "consumer type", hence IBasicConsumer is sufficient.

**Comment by lukebakken** [comment]
> but should the name itself be IAsyncBasicConsumer

Yes, use that name. Thanks.

**Comment by michaelklishin** [comment]
I agree that `IAsyncBasicConsumer` is perfectly fine to use as the name, to make it very obvious what this new "unified" implementation is like.

**Review by lukebakken — APPROVED** [review]
Thank you!

**Pull request merged**
