### PR TITLE
Removed ReceiveBufferSize and SendBufferSize to improve message rates

### PR DESCRIPTION
**Pull request by MarcoZuiderwijkBS**
## Proposed Changes

When connecting our application running in the Western Europe region to a RabbitMQ instance in the East-US region we got a very low message rate (12 messages per second). Message size is around 80kb. We also tested this with a Python (using pika 1.3.2) and a Java consumer (using amqp-client 5.16.0) which had a much higher message rate (> 500 messages per second). We also did a test with RabbitMQ version 5.2.0 and to our surprise this also had a much higher message rate.

My colleague Joey Bleeker investigated the differences between version 5.2.0 and 6.6.0 of the RabbitMQ Client and found this [commit](https://github.com/rabbitmq/rabbitmq-dotnet-client/commit/ff627be358269985da306ca0e76a0e7a962b4366). We removed the setting for the ReceiveBufferSize and SendBufferSize. This gives the latest RabbitMQ.Client the same performance as the version 5.2.0. The previous changes seems to conflict with the TCP [Window Scaling](https://learn.microsoft.com/en-us/troubleshoot/windows-server/networking/description-tcp-features#windows-scaling). 

## Types of Changes

What types of changes does your code introduce to this project?
_Put an `x` in the boxes that apply_

- [x] Bug fix (non-breaking change which fixes issue #NNNN)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause an observable behavior change in existing systems)
- [ ] Documentation improvements (corrections, new content, etc)
- [ ] Cosmetic change (whitespace, formatting, etc)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating
the PR. If you're unsure about any of them, don't hesitate to ask on the
mailing list. We're here to help! This is simply a reminder of what we are
going to look for before merging your code._

- [x] I have read the `CONTRIBUTING.md` document
- [ ] I have signed the CA (see https://cla.pivotal.io/sign/rabbitmq)
- [ ] All tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in related repositories

## Further Comments

If this is a relatively large or complex change, kick off the discussion by
explaining why you chose the solution you did and what alternatives you
considered, etc.

### CODE REVIEW

**Comment by michaelklishin** [comment]
@MarcoZuiderwijkBS thank you for digging in.

As https://github.com/rabbitmq/rabbitmq-dotnet-client/commit/ff627be358269985da306ca0e76a0e7a962b4366 mentions, some workload may benefit from these settings, while your workload with messages much larger than average suffers.

Sounds like it should be a configurable settings and not something we flip back and forth.

At least several other clients allow you to "post-configure" a socket before it connects using
a lambda. I'd suggest something like that, with the default being "no configuration besides Nagle's algorithm".

**Comment by lukebakken** [comment]
Converting to draft just to ensure this isn't merged prematurely.

**Comment by lukebakken** [comment]
We should adopt what the Java client does to configure the underlying Socket:

https://github.com/rabbitmq/rabbitmq-java-client/blob/main/src/main/java/com/rabbitmq/client/SocketConfigurator.java

**Comment by lukebakken** [comment]
@MarcoZuiderwijkBS I've merged your code into https://github.com/rabbitmq/rabbitmq-dotnet-client/pull/1415. Since your PR is on the `main` branch I can't easily make modifications to it.

**Comment by lukebakken** [comment]
@MarcoZuiderwijkBS FYI you can work around the current issue by creating your `ConnectionFactory` this way:

```
ConnectionFactory cf = new()
{
    SocketFactory = (AddressFamily af) =>
    {
        var socket = new Socket(af, SocketType.Stream, ProtocolType.Tcp)
        {
            NoDelay = false
        };
        return new TcpClientAdapter(socket);
    }
};
```

**Comment by lukebakken** [comment]
@MarcoZuiderwijkBS https://www.nuget.org/packages/RabbitMQ.Client/6.7.0-rc.1

**Pull request closed without merging**
