### PR TITLE
Switch to Verify for API approval test

### LINKED ISSUE #815: API Approval tests are skipped
In master, when I run

``` shell
dotnet test projects/Unit --filter "FullyQualifiedName~RabbitMQ.Client.Unit.APIApproval"
```

then the test reports that it has unsufficient source symbol information or something of that kind and stops with a fairly specific set of recommendations:

```
dotnet test projects/Unit --filter "FullyQualifiedName~RabbitMQ.Client.Unit.APIApproval"
/Users/antares/.nuget/packages/microsoft.build.tasks.git/1.0.0/build/Microsoft.Build.Tasks.Git.targets(24,5): warning : Could not find file '/Users/antares/Development/RabbitMQ/umbrella.git/deps/rabbitmq_dotnet_client/_site/.git'. The source code won't be available via Source Link. [/Users/antares/Development/RabbitMQ/umbrella.git/deps/rabbitmq_dotnet_client/projects/RabbitMQ.Client/RabbitMQ.Client.csproj]
/Users/antares/.nuget/packages/microsoft.build.tasks.git/1.0.0/build/Microsoft.Build.Tasks.Git.targets(24,5): warning : Could not find file '/Users/antares/Development/RabbitMQ/umbrella.git/deps/rabbitmq_dotnet_client/_site/.git'. The source code won't be available via Source Link. [/Users/antares/Development/RabbitMQ/umbrella.git/deps/rabbitmq_dotnet_client/projects/RabbitMQ.Client/RabbitMQ.Client.csproj]
Test run for /Users/antares/Development/RabbitMQ/umbrella.git/deps/rabbitmq_dotnet_client/projects/Unit/bin/Debug/net461/Unit.dll(.NETFramework,Version=v4.6.1)
Microsoft (R) Test Execution Command Line Tool Version 16.3.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...

A total of 1 test files matched the specified pattern.
  X Approve [430ms]
  Error Message:
   System.Exception :
ApprovalTests is not detecting the proper source path

This is probably because you're missing the following
line in your .csproj file:
	  <DebugType>full</DebugType>
in the
<Project>
  <PropertyGroup>
element.

Solution:
a) Add <DebugType>full</DebugType> to your .csproj file.
b) OR Build->Advanced->DebugInfo to Full
  Stack Trace:
    at ApprovalTests.Namers.StackTraceParsers.StackTraceParser.get_SourcePath () [0x00033] in <09be150c07864de7bafbca0757a4fd61>:0
  at ApprovalTests.Namers.UnitTestFrameworkNamer.get_SourcePath () [0x00000] in <09be150c07864de7bafbca0757a4fd61>:0
  at ApprovalTests.Approvers.FileApprover.Approve () [0x00001] in <09be150c07864de7bafbca0757a4fd61>:0
  at ApprovalTests.Core.Approver.Verify (ApprovalTests.Core.IApprovalApprover approver, ApprovalTests.Core.IApprovalFailureReporter reporter) [0x00001] in <09be150c07864de7bafbca0757a4fd61>:0
  at ApprovalTests.Approvals.Verify (ApprovalTests.Core.IApprovalApprover approver, ApprovalTests.Core.IApprovalFailureReporter reporter) [0x00001] in <09be150c07864de7bafbca0757a4fd61>:0
  at ApprovalTests.Approvals.Verify (ApprovalTests.Core.IApprovalWriter writer, ApprovalTests.Core.IApprovalNamer namer, ApprovalTests.Core.IApprovalFailureReporter reporter) [0x00044] in <09be150c07864de7bafbca0757a4fd61>:0
  at ApprovalTests.Approvals.Verify (ApprovalTests.Core.IApprovalWriter writer) [0x0000f] in <09be150c07864de7bafbca0757a4fd61>:0
  at ApprovalTests.Approvals.VerifyWithExtension (System.String text, System.String fileExtensionWithDot, System.Func`2[T,TResult] scrubber) [0x00059] in <09be150c07864de7bafbca0757a4fd61>:0
  at ApprovalTests.Approvals.Verify (System.String text, System.Func`2[T,TResult] scrubber) [0x00001] in <09be150c07864de7bafbca0757a4fd61>:0
  at RabbitMQ.Client.Unit.APIApproval.Approve () [0x00032] in <729deeb8484847dcabbc2e050a761992>:0
  at (wrapper managed-to-native) System.Reflection.RuntimeMethodInfo.InternalInvoke(System.Reflection.RuntimeMethodInfo,object,object[],System.Exception&)
  at System.Reflection.RuntimeMethodInfo.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x0006a] in <b6f643ae6ccb410db69142d5eaf9b9c1>:0

Test Run Failed.
Total tests: 1
     Failed: 1
 Total time: 1.8044 Seconds
Test run for /Users/antares/Development/RabbitMQ/umbrella.git/deps/rabbitmq_dotnet_client/projects/Unit/bin/Debug/netcoreapp3.1/Unit.dll(.NETCoreApp,Version=v3.1)
Microsoft (R) Test Execution Command Line Tool Version 16.3.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...

A total of 1 test files matched the specified pattern.

Test Run Successful.
Total tests: 1
     Passed: 1
 Total time: 1.3850 Seconds
```

My .NET build system knowledge is nearly non-existent so I'm not sure what would be the best way to address this. My guess is that this started with #797 and related changes for `6.0`.

### PR DESCRIPTION
**Pull request by bording**
This switches a different approval library for the API approval test. Verify doesn't require special project settings to work in all scenarios like ApprovalTests does.

Fixes #815

### CODE REVIEW

**Comment by bording** [comment]
> Thank you. On MacOS, the .NET 4.6.1 version fails with

You really shouldn't be trying to run the 4.6.1 tests on non-Windows OSes. That will try to run them on mono, and who knows if that will work.

**Comment by michaelklishin** [comment]
Fair enough. I have added a pragma to skip this test. If we run into more Mono-specific issues we can consider doing this for all tests. I'm not sure what would be the best way to do that with NUnit, though.

**Comment by bording** [comment]
Please don't skip the text on 4.6.1, it's important it runs on both. 

You just need to not run the 4.6.1 tests when you're not on Windows.

**Comment by michaelklishin** [comment]
@bording OK, how do I do that? `dotnet test` currently runs them against both targets.

**Comment by bording** [comment]
> Should we make this approval test specific to .NET Core to avoid such issues? It would still serve its purpose.

Since there are separate assemblies for each target framework, it's actually possible that there could be unintentional differences in the public API surface, for example through `#define`s being introduced. That's why it's important to run the test against both assemblies to make sure they are the same.

> @bording OK, how do I do that? dotnet test currently runs them against both targets.


`dotnet test -f netcoreapp3.1`

**Comment by michaelklishin** [comment]
@bording I will skip the test only on Mono then. Adding `-f netcoreapp3.1` is something our team can keep in mind but we need to keep `dotnet test` passing [when there are no actual behavior changes) for external contributors. How does that sound?

**Comment by bording** [comment]
> @bording I will skip the test only on Mono then

Why do you care about mono at all at this point? It's not clear to me why you'd even be attempting to run any tests on mono now.

Are you saying that you have been running the test suite with mono previously?

**Comment by lukebakken** [comment]
> Are you saying that you have been running the test suite with mono previously?

Yes, prior to all of the changes for `5.2.0` / `6.0.0` when `net451` was one of the target frameworks. But now, Mono should not be used anywhere (@michaelklishin). I'll double-check on my OS X machine. I think we can remove anything Mono-specific in the codebase. I'll open a PR for that.

**Comment by michaelklishin** [comment]
I use .NET Core on MacOS. Windows is not the primary development environment for our team (although we obvious test on it).

How can I run tests on .NET 4.6.1 on MacOS?

**Comment by bording** [comment]
> How can I run tests on .NET 4.6.1 on MacOS?

That's the point I'm trying to make. There is no compelling reason to try and run .NET Framework tests on non-Windows operating systems now that .NET Core exists.

**Comment by michaelklishin** [comment]
OK, then it makes sense to exclude them and only run against .NET Core (which has been the case until we went multi-target recently?).

**Comment by bording** [comment]
> OK, then it makes sense to exclude them and only run against .NET Core (which has been the case until we went multi-target recently?).

What do you mean by exclude them? You still need to run them on Windows.

What problem are you trying to solve exactly? It's not clear to me what you're trying to do?

**Comment by michaelklishin** [comment]
`dotnet test` currently executes tests twice on MacOS, once for every target. It would be nice to only have a single .NET Core run everywhere other than Windows.

**Comment by bording** [comment]
That's why you should use the `-f` parameter I pointed out. You can add that to a script if you don't want to type it all the time.

**Comment by bording** [comment]
Actually, that's already in the [run-test.sh](https://github.com/rabbitmq/rabbitmq-dotnet-client/blob/master/run-test.sh#L16) script.

**Comment by lukebakken** [comment]
Thanks for pointing that out @bording 

@michaelklishin we can expand `run-test.sh` to pass on arguments to `dotnet test` to allow for filtering or what-not

**Comment by michaelklishin** [comment]
I see, so I have to use `-f` all the time. That's fine, no need to modify `run-test.sh`. I have amended the examples to use `-f` so that they do the same thing on all platforms. Hopefully .NET Core alone should provide sufficiently good coverage most of the time.

**Pull request merged**
