### PR TITLE
Various cleanups of Connection / Model

### PR DESCRIPTION
**Pull request by bollhals**
## Proposed Changes

various smaller cleanups mainly in connection and model classes.
- change access modifier to public if they're really public, internal if only called from within the lib, protected/private otherwise.
- removed old ifdef !NETSTANDARD1.5
- move DebugUtil out of lib code to the test class
- removed various unused types / methods
- removed IFullModel as it could either be used as ModelBase or it was test code
- removed unset property of IConnection
- removed 2 methods in IConnection, that should've been internal

## Types of Changes

- [ ] Bug fix (non-breaking change which fixes issue #NNNN)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause an observable behavior change in existing systems)
- [ ] Documentation improvements (corrections, new content, etc)
- [ ] Cosmetic change (whitespace, formatting, etc)

## Checklist

- [x] I have read the `CONTRIBUTING.md` document
- [x] I have signed the CA (see https://cla.pivotal.io/sign/rabbitmq)
- [ ] All tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in related repositories

## Further Comments

This PR contains some small public API changes!

### CODE REVIEW

**Comment by bollhals** [comment]
Size of lib drops for me from `213 KB (218'624 Bytes)` -> `206 KB (211'456 Bytes)`

**Review by michaelklishin — APPROVED** [review]

**Comment by michaelklishin** [comment]
@bollhals this now needs a rebase against master 🙏

**Comment by bollhals** [comment]
> @bollhals this now needs a rebase against master 🙏

done 👍

**Comment by michaelklishin** [comment]
…and this now needs another rebase.

**Comment by bollhals** [comment]
Will do 😃

**Comment by bollhals** [comment]
done 👍  this should be ready

**Comment by bollhals** [comment]
Can we proceed with this or is there something to look at?

**Comment by bollhals** [comment]
@michaelklishin can we proceed with this?

**Pull request merged**
