### PR TITLE
Make IQueueingConsumer and ISubscription public

### LINKED ISSUE #47: Make IQueueingBasicConsumer and ISubscription public
I am trying to have some cases covered by tests, some of the interfaces I need to mock are made internal in the solution (e.g. I would like to mock IQueueingBasicConsumer). 
Is there any reason for interfaces like IQueueingBasicConsumer, ISubscription not being exposed?

### PR DESCRIPTION
**Pull request by michaelklishin**
Fixes #47.

### CODE REVIEW

**Comment by abellix** [comment]
awesome, thank you

**Comment by abellix** [comment]
any idea of when the nuget package is going to be released? Is there any nightly build available?

**Comment by michaelklishin** [comment]
NuGet packages are released a few days after RabbitMQ releases. We do have [nightly builds](https://www.rabbitmq.com/nightly-builds.html).

**Comment by abellix** [comment]
Any idea of when is it planned the next RabbitMQ release?

**Comment by michaelklishin** [comment]
Patch releases come out roughly once a month.

**Pull request merged**
