### PR TITLE
Make it possible to use a Docker-provided RabbitMQ node for tests

### PR DESCRIPTION
**Pull request by michac**
## Proposed Changes

I was unable to get the umbrella project running locally to run the unit tests against. However, I was able to make some changes to the Fixtures.cs file to support using a docker instance of rabbit. My test sequence is:

* `docker run -d --hostname rabbitmq01 --name rabbitmq01 -p 15672:15672 -p 5672:5672 rabbitmq:3-management`
* set my `RABBITMQ_RABBITMQCTL_PATH` env variable to `DOCKER:rabbitmq01`
* run unit tests

I figured since I had the changes working I'd submit there here to see if you were interested.

## Types of Changes

What types of changes does your code introduce to this project?
_Put an `x` in the boxes that apply_

- [ ] Bug fix (non-breaking change which fixes issue #NNNN)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause an observable behavior change in existing systems)
- [ ] Documentation improvements (corrections, new content, etc)
- [ ] Cosmetic change (whitespace, formatting, etc)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating
the PR. If you're unsure about any of them, don't hesitate to ask on the
mailing list. We're here to help! This is simply a reminder of what we are
going to look for before merging your code._

- [x] I have read the `CONTRIBUTING.md` document
- [x] I have signed the CA (see https://cla.pivotal.io/sign/rabbitmq)
- [x] All tests pass locally with my changes
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in related repositories

## Further Comments

This could be enhanced to actually create an appropriately versioned docker container and tear it down when done so the unit tests just work if you have docker available, but this change doesn't do anything that fancy.

### CODE REVIEW

**Comment by michaelklishin** [comment]
This looks reasonable to me. Let's see what @kjnilsson @lukebakken say.

**Comment by kjnilsson** [comment]
yep this is handy, thanks!

**Comment by michaelklishin** [comment]
We can add a minimalistic `Dockerfile` that uses https://github.com/docker-library/rabbitmq/ with all defaults. It should be sufficient for this test suite.

**Comment by michac** [comment]
To be clear on the requested changes, I could
a. Document the two manual setup steps I listed above, which might be sufficient if using umbrella continues to be the standard approach and docker is just a backup option.
b. Integrate the run command into the unit tests such that it deploys a container to run the tests then  cleans it up afterwards. This would require a little research on my part for best practices, I've never integrated docker with unit tests like that. This makes more sense to me if you think Docker may become the standard approach in the long term.

**Comment by michaelklishin** [comment]
@michac thank you!

Please use a separate script/target for that. The `./run-tests` we have is used by CI which provisions a node separately. Our team runs RabbitMQ locally and not in a container during client development, too.

**Comment by michac** [comment]
@michaelklishin I wasn't very clear in my comment. What I was asking was whether I should do a OR b. 
I would do option a if I'm the only one who will use it or option b if you think it's worth a little polish and others may use it too.
If I did option b I figured I would still operate based off of the environment variable and just have the test do setup and teardown if docker was specified.

**Comment by TrymBeast** [comment]
Hey guys!
How about having a docker file that builds & runs the tests and a docker compose that builds the docker file and also declares the rabbitmq container as dependency?

**Comment by michaelklishin** [comment]
@TrymBeast that's a reasonable idea, even though I expect many contributors would not mind running the suite in the host (and on different platforms).

**Comment by michaelklishin** [comment]
@michac I would be happy with option A. If this topic seems interesting to you, feel free to investigate. If it takes too long, option A would still be there ;)

**Comment by michac** [comment]
I'm not sure if I'll find time to do anything fancier with Docker, so I just went ahead and updated the documentation in this pull request.

**Pull request merged**
