### PR TITLE
Add custom filtering and exception handling to topology recovery

### LINKED ISSUE #658: Exception during recovery causes recovery failure
I've run into an issue where an exception happens after recovery which causes the connection to be closed and no attempt to recover.

As far as I can tell from logs this is what's happening

- `RecoverySucceeded` event raised
- `ModelShutdown` event raised with close reason 530 NOT_ALLOWED
- Connection is closed but `ConnectionShutdown` event is not raised

From a quick look over the code it seems like the problem is here:

https://github.com/rabbitmq/rabbitmq-dotnet-client/blob/015c51761deabfebe03e3bff2c4eb4e2ab53a072/projects/client/RabbitMQ.Client/src/client/impl/Connection.cs#L575-L586

There is already a close reason set but there is another exception happening

Here is the full exception taken from `m_shutdownReport`

```
Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host.
   at RabbitMQ.Client.Impl.InboundFrame.ReadFrom(NetworkBinaryReader reader)
   at RabbitMQ.Client.Framing.Impl.Connection.MainLoopIteration()
   at RabbitMQ.Client.Framing.Impl.Connection.ClosingLoop()
```

### PR DESCRIPTION
**Pull request by rosca-sabina**
Fixes #658 

## Proposed Changes

This PR introduces changes that address issue #658. The changes I made are based on @acogoluegnes's suggestion of adapting the features related to topology recovery included in the Java client.

For topology recovery filtering, I added class `TopologyRecoveryFilter`, which is initialized at the `ConnectionFactory` level. It allows users to specify filters for each type of recorded entity (exchanges, queues, bindings, consumers). During topology recovery, the recorded entities will or won't be recovered based on whether they match the condition specified in the `TopologyRecoveryFilter` or not. If no filter is specified for an entity type, all entities of that type will be recovered.

For exception handling, I added class `TopologyRecoveryExceptionHandler`, which is also initialized at the `ConnectionFactory` level. For each type of recorded entity, it allows users to provide: a custom exception handler, which defines what action is taken in the case of an exception, and a condition, which determines what exceptions the custom exception handler applies to. If no custom exception handler is specified for an entity type, the default exception handling behavior (defined in `HandleTopologyRecoveryException()`) is used for all exceptions.

## Types of Changes

What types of changes does your code introduce to this project?

- [x] Bug fix (non-breaking change which fixes issue #658)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause an observable behavior change in existing systems)
- [ ] Documentation improvements (corrections, new content, etc)
- [ ] Cosmetic change (whitespace, formatting, etc)

## Checklist

- [x] I have read the `CONTRIBUTING.md` document
- [x] I have signed the CA (see https://cla.pivotal.io/sign/rabbitmq)
- [x] All tests pass locally with my changes
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in related repositories

### CODE REVIEW

**Comment by rosca-sabina** [comment]
Hello,

I noticed the Concourse CI build failed after my latest commit (I rebased from main after the model -> channel rename was merged).

Could anyone let me know if there's anything on my side I should do to get the build to pass? The build seemed to hang (it took 30 minutes), but if there are failing tests I'll take a look if you can tell me which ones failed.

Thanks!

**Comment by lukebakken** [comment]
@rosca-sabina the Concourse build is notoriously flaky!

**Comment by rosca-sabina** [comment]
Ah, I see. Thanks for re-running it!

**Review by lukebakken — APPROVED** [review]
Thank you! I'll wait for @Zerpet to merge.

**Comment by rosca-sabina** [comment]
Thank you for the code review and approval! 

One question: After we get @Zerpet 's feedback and this is merged to main, if I provide a backport of this feature to 6.x, would it be possible for it to be released as some sort of patch to 6.4.0, like a 6.4.1? 

It would really help me out to be able to use this on a project I'm working on, and it would be helpful to know if it would be feasible to have it available sooner, or if I'd have to wait for release 6.5.0 instead.

**Comment by lukebakken** [comment]
@rosca-sabina this change requires the next version to be 6.5.0. If you'd like to open a PR now against 6.x with these changes back-ported, that would be helpful. I don't expect there to be any changes requested to this PR.

**Comment by rosca-sabina** [comment]
I see, I'll get started on the backport then.

Also, I hit the re-review button by mistake, my bad.

**Comment by rosca-sabina** [comment]
And here is the backport to 6.x: #1316.

Just to make sure I understand correctly: when you say this change requires the version to be 6.5.0, do you mean that the minor version, and not the patch, needs to be incremented to respect semantic versioning? Or did you mean that this feature would have to be released as part of milestone 6.5.0, together with all of the other fixes/features that the milestone currently includes?

**Comment by rosca-sabina** [comment]
@lukebakken I see, thanks for the clarification!

@Zerpet I just noticed my accidentally clicking re-review removed you as a reviewer. That was my bad, didn't mean to click it. Please feel free to leave your feedback when you can.

**Review by Zerpet — APPROVED** [review]

**Comment by Zerpet** [comment]
@lukebakken since the backport #1316 is for `6.5.0`, shall we mark this PR for `7.0.0` ?

The idea is to track this enhancement in the release notes, when we decide to ship 7.0.

**Comment by lukebakken** [comment]
>  shall we mark this PR for 7.0.0

@Zerpet good catch

**Pull request merged**
