### PR TITLE
Fixing possible premature disposal of pooled memory

### PR DESCRIPTION
**Pull request by stebet**
## Proposed Changes

This should fix an issue where pooled memory used in message bodies might be prematurely disposed. This is fixed by copying the message body when work is scheduled and disposing the new pool when the job processing is completed.

## Types of Changes

What types of changes does your code introduce to this project?
- [X] Bug fix (non-breaking change which fixes issue #802)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause an observable behavior change in existing systems)
- [ ] Documentation improvements (corrections, new content, etc)
- [ ] Cosmetic change (whitespace, formatting, etc)

## Checklist

- [X] I have read the `CONTRIBUTING.md` document
- [X] I have signed the CA (see https://cla.pivotal.io/sign/rabbitmq)
- [X] All tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in related repositories

### CODE REVIEW

**Comment by michaelklishin** [comment]
@Anarh2404 may I ask you to give this PR a shot against your test case? Thank you 🙏

**Comment by michaelklishin** [comment]
@stebet incredible turnaround time for Friday evening 💪

**Comment by stebet** [comment]
> @stebet incredible turnaround time for Friday evening 💪

Let's see it work first :P

**Comment by lukebakken** [comment]
Thanks @stebet. I've included your changes in #804 as well as the test changes from #802 but it seems there are some build failures in other areas. I'm investigating.

**Pull request closed without merging**
