### PR TITLE
Use self describing event source format for .NET core only

### PR DESCRIPTION
**Pull request by kjnilsson**
Only simple error logging is supported for net451

Remove Microsoft.Diagnostics.Tracing.EventSource.Redist dependency for net451

### CODE REVIEW

**Comment by kjnilsson** [comment]
@kforbesni - here is a PR to remove the event source dependency for net451 - I have only been able  to test it for .NET core - are you able to give this a test on net451?

@bording - WDYT?

**Comment by bording** [comment]
@kjnilsson LGTM 

I tried out the `RabbitMqConsoleEventListener` with a `net451` project, and everything appears to be working fine. Being able to remove a dependency is always a good thing!

The downside of this change is that it's definitely a breaking change. If this goes in, the version should definitely be bumping to 6.0.0.

**Comment by kjnilsson** [comment]
Thanks for checking!

Breaking because of the change to the Error method? Would anyone really
depend on this?

**Comment by bording** [comment]
@kjnilsson It's not just the Error method. The base types of all of those classes have changed from the ones in the package to the ones in the Framework, so they are completely different types now from a binary compatibility standpoint.

**Comment by kjnilsson** [comment]
This has been merged in (with a rebased commit which is why it didn't auto close).

**Pull request closed without merging**
