### PR TITLE
Align Reject with Ack/Nack

### PR DESCRIPTION
**Pull request by danielmarbach**
## Proposed Changes

See https://github.com/rabbitmq/rabbitmq-dotnet-client/issues/1413#issuecomment-2258285842

## Types of Changes

What types of changes does your code introduce to this project?
_Put an `x` in the boxes that apply_

- [ ] Bug fix (non-breaking change which fixes issue #NNNN)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause an observable behavior change in existing systems)
- [ ] Documentation improvements (corrections, new content, etc)
- [ ] Cosmetic change (whitespace, formatting, etc)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating
the PR. If you're unsure about any of them, don't hesitate to ask on the
mailing list. We're here to help! This is simply a reminder of what we are
going to look for before merging your code._

- [x] I have read the `CONTRIBUTING.md` document
- [x] I have signed the CA (see https://cla.pivotal.io/sign/rabbitmq)
- [ ] All tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in related repositories

## Further Comments

If this is a relatively large or complex change, kick off the discussion by
explaining why you chose the solution you did and what alternatives you
considered, etc.

### CODE REVIEW

**Review by lukebakken — APPROVED** [review]
Good catch

**Comment by Tornhoof** [comment]
I wonder if the split between ValueTask and Task makes sense at all here, I could not really find any async methods doing the
```csharp
if(valueTask.IsCompletedSuccessfuly) 
{
  return FastPath();
}
else 
{
  return SlowAwaitPath();
}
```

dance, or anything in a really tight loop where the above should be used.

**Comment by danielmarbach** [comment]
@Tornhoof I commented on the umbrella issue that I'm not sure if the valuetask vs task has further been thought through. Currently the entire Channel -> Session -> Connection -> Frame -> ChannelWriter exposes the underlying channelwriter value task and that is a choice that I think is fine. What is confusing right now is that are public APIs that are essentially doing ValueTask all the way through the hierarchy while others don't. 

This PR does at least align the methods that call into ModelSendAsync

**Comment by danielmarbach** [comment]
For example I also do not understand why when `WriteAsync` on the framehandler is returning a value task the corresponding `SendProtocolHeaderAsync` is not

**Comment by lukebakken** [comment]
> What is confusing right now is that are public APIs that are essentially doing ValueTask all the way through the hierarchy while others don't.

If there are other changes you suggest, feel free to point them out and I'll take a look, or open new PRs.

It has been a while since I looked at this in detail, but I remember trying to avoid conversion from ValueTask -> Task.

**Comment by lukebakken** [comment]
> For example I also do not understand why when WriteAsync on the framehandler is returning a value task the corresponding SendProtocolHeaderAsync is not

There's no good reason that I can see! Feel free to make a list and I can address this. I'll open an issue to track this.

**Pull request merged**
