### PR TITLE
Pipeline improvements

### PR DESCRIPTION
**Pull request by Anarh2404**
## Proposed Changes

This PR based on awesome @stebet  work in #706
I made some improvements and achieved even greater reduction in memory consumption and increased performance.
Here is what I did:
- Reduce the number of async paths (which generates AsyncStateMachine) in pipeline reader 
- Improve binary readers/writers 

All tests run, except for the APIApproval

## Types of Changes

- [ ] Bug fix (non-breaking change which fixes issue #NNNN)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause an observable behavior change in existing systems)
- [ ] Documentation improvements (corrections, new content, etc)
- [x] Cosmetic change (whitespace, formatting, etc)

## Checklist

- [x] I have read the `CONTRIBUTING.md` document
- [x] I have signed the CA (see https://cla.pivotal.io/sign/rabbitmq)
- [ ] All tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in related repositories

## Further Comments
I added netstandard2.1 and few #if derectives, because some perf critical API is only available in the netstandard2.1/netcoreapp3.0. For netstandard2.0 and net461 added fallback to a less optimal implementation.

### Memory test
**512byte payload**
#706 
stebet_pr
This PR 
my_pr

### Simple perfomance test on my home pc

**1 publisher, 1 consumer, no ack**
Nuget 5.1.2
5 1 2_no_ack
#706 
stebet_no_ack
This PR
my_pr_no_ack

**1 publisher, 1 consumer, manual ack, 64 prefetch count**
Nuget 5.1.2
5 1 2_manual_ack_64_prefetch_count
#706 
stebet_manual_ack_64_prefetch_count
This PR
my_pr_manual_ack_64_prefetch_count

### CODE REVIEW

**Review by michaelklishin — CHANGES_REQUESTED** [review]
Thank you. Please remove the test program. Publishing it in a separate repo under your account should be sufficient.

**Comment by michaelklishin** [comment]
Please rebase this against master.

Out of curiosity, do most of the gains come from the switch to `BinaryBufferReader`? Or the reduced number of pipeline paths

**Comment by lukebakken** [comment]
@Anarh2404 thanks for this pull request.

We can't merge this pull request as-is into `master`. You should open your pull request against the `allocationImprovements` branch in the https://github.com/stebet/rabbitmq-dotnet-client.git` fork of this repository.

Or, @stebet - would you mind reviewing these changes and, if acceptable, merge them into your `stebet:allocationImprovements` fork & branch? Thanks.

**Comment by lukebakken** [comment]
@stebet - and by "these changes" I mean the changes in @Anarh2404 's commit: https://github.com/rabbitmq/rabbitmq-dotnet-client/pull/734/commits/3147ab5cfe21b63dd24380140cbbe74203ca4aa1

**Comment by stebet** [comment]
I'll take a look tomorrow :)

**Comment by Anarh2404** [comment]
@michaelklishin `BinaryBufferReader` has reduced memory consumption, but not only it. Reduction of async paths increased throughput.

@lukebakken @stebet I think it would be nice if this PR would be merged into a `stebet:allocationImprovements`, of course, if this acceptable.

**Comment by Anarh2404** [comment]
Made a test branch where i merged this PR and #732 :)

test_branch

**Comment by Anarh2404** [comment]
@michaelklishin test program from the #706

**Comment by lukebakken** [comment]
I am assuming that the changes in this PR will be investigated for version `7.0.0`

**Pull request closed without merging**
