### PR TITLE
Use file-scoped namesapces in RabbitMQ.Client project

### PR DESCRIPTION
**Pull request by ArminShoeibi**
## Proposed Changes
Hi there folks.
this merge request changes old namespaces to file-scoped namespaces in RabbitMQ.Client project.
if we want to change other projects such as tests and samples we need to drop net4.7.2 support.

## Types of Changes

What types of changes does your code introduce to this project?
_Put an `x` in the boxes that apply_

- [ ] Bug fix (non-breaking change which fixes issue #NNNN)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause an observable behavior change in existing systems)
- [ ] Documentation improvements (corrections, new content, etc)
- [x] Cosmetic change (whitespace, formatting, etc)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating
the PR. If you're unsure about any of them, don't hesitate to ask on the
mailing list. We're here to help! This is simply a reminder of what we are
going to look for before merging your code._

- [x] I have read the `CONTRIBUTING.md` document
- [x] I have signed the CA (see https://cla.pivotal.io/sign/rabbitmq)
- [x] All tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in related repositories

## Further Comments

Tests of net472
Before:
net472-tests-before

After:
net472-tests-after

Tests of net6.0 
Before:
net6-tests-before

After:
net6-tests-after

### CODE REVIEW

**Comment by michaelklishin** [comment]
@ArminShoeibi thank you for taking the time. What's the minimum .NET requirement with this change? I see it requires C# 10 but we express requirements in terms of .NET release series. I am not sure we can drop 4.7 at this point, although there were recent discussions about going to 4.8 or 5.0.

Using old style namespaces in tests and examples is OK. We need to understand what this PR means for version requirements before merging.

**Comment by michaelklishin** [comment]
I see our tests already target .NET 6.0. Nice. [RUNNING_TESTS.md](https://github.com/rabbitmq/rabbitmq-dotnet-client/blob/main/RUNNING_TESTS.md) is now up-to-date for May 2022, with the potential exception of running individual tests.

@ArminShoeibi I'm quite sure the test failures you see require a locally running RabbitMQ
node as I don't get any in `main`:

```
Test Run Successful.
Total tests: 252
     Passed: 246
    Skipped: 6
 Total time: 10.1903 Minutes
```

**Comment by michaelklishin** [comment]
All tests pass on this branch as well:

```
Test Run Successful.
Total tests: 252
     Passed: 246
    Skipped: 6
 Total time: 10.3054 Minutes
```

**Review by michaelklishin — APPROVED** [review]

**Comment by michaelklishin** [comment]
Found the supported minimum version discussion: https://github.com/rabbitmq/rabbitmq-dotnet-client/pull/1189.

**Comment by ArminShoeibi** [comment]
> I see our tests already target .NET 6.0. Nice. [RUNNING_TESTS.md](https://github.com/rabbitmq/rabbitmq-dotnet-client/blob/main/RUNNING_TESTS.md) is now up-to-date for May 2022, with the potential exception of running individual tests.
> 
> @ArminShoeibi I'm quite sure the test failures you see require a locally running RabbitMQ node as I don't get any in `main`:
> 
> ```
> Test Run Successful.
> Total tests: 252
>      Passed: 246
>     Skipped: 6
>  Total time: 10.1903 Minutes
> ```

Oh I got it, So I needed a RabbitMQ node on my localhost
Thank you dear Michael @michaelklishin

**Comment by michaelklishin** [comment]
@ArminShoeibi @lukebakken should we backport this to `7.x`? The milestone says so, and it would be much easier to backport all future changes from `main` to `7.x` if we do.

I can spend some time on doing that if you agree (and no one else volunteers!)

**Comment by ArminShoeibi** [comment]
> 

I'm okay with that.

**Comment by ArminShoeibi** [comment]
> @ArminShoeibi @lukebakken should we backport this to `7.x`? The milestone says so, and it would be much easier to backport all future changes from `main` to `7.x` if we do.
> 
> I can spend some time on doing that if you agree (and no one else volunteers!)

I'm okay with it.

**Comment by michaelklishin** [comment]
I run into

```
projects/RabbitMQ.Client/client/api/IBasicConsumer.cs(98,13): error CS0246: The type or namespace name 'ReadOnlyMemory<>' could not be found
```

as soon as I change any or all `.csproj` files to use

``` xml
<TargetFrameworks>net6.0;netstandard2.0</TargetFrameworks>
<LangVersion>latest</LangVersion>
```

on the `7.x` branch. Since [`ReadOnlyMemory<>`](https://docs.microsoft.com/en-us/dotnet/api/system.readonlymemory-1?view=net-6.0) comes from the `System.Runtime` assembly,
I am not sure what reference or import may be missing.

**Comment by michaelklishin** [comment]
I concluded that we should revert this. It's a nice feature but it makes backports of PRs between branches impossible unless they all use it, and it requires C# 10, which means all branches we support in any capacity can't adopt it.

**Pull request merged**
