### PR TITLE
change from Memory to ReadOnlyMemory

### PR DESCRIPTION
**Pull request by bollhals**
## Proposed Changes

Aligns the type to the usage (None of them actually should modify the memory, as we're sending it, hence it should be read only.) Also the usage of  
`MemoryMarshal.TryGetArray<T>(ReadOnlyMemory<T>, ArraySegment<T>)`
requires a ReadOnlyMemory not Memory.

## Types of Changes

- [ ] Bug fix (non-breaking change which fixes issue #NNNN)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause an observable behavior change in existing systems)
- [ ] Documentation improvements (corrections, new content, etc)
- [ ] Cosmetic change (whitespace, formatting, etc)

## Checklist

- [x] I have read the `CONTRIBUTING.md` document
- [x] I have signed the CA (see https://cla.pivotal.io/sign/rabbitmq)
- [ ] All tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in related repositories

### CODE REVIEW

**Review by michaelklishin — APPROVED** [review]

**Comment by michaelklishin** [comment]
Thank you!

**Comment by michaelklishin** [comment]
@bollhals should this be backported to `6.x`?

**Comment by michaelklishin** [comment]
@bollhals this can be a candidate for backporting to `6.x`. WDYT?

**Comment by bollhals** [comment]
Yes this could be backported, but there's not much gain from it either. It's more consistency than anything else really.

**Comment by michaelklishin** [comment]
OK

**Pull request merged**
