### PR TITLE
chore: bump regular System.Text.RegularExpressions due to a known CVE in earlier versions

### PR DESCRIPTION
**Pull request by aygalinc**
## Proposed Changes

Add explicit dependencies due to cve on System.Text.RegularExpressions 

## Types of Changes

What types of changes does your code introduce to this project?
_Put an `x` in the boxes that apply_

- [X] Bug fix (non-breaking change which fixes issue #NNNN)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause an observable behavior change in existing systems)
- [ ] Documentation improvements (corrections, new content, etc)
- [ ] Cosmetic change (whitespace, formatting, etc)

### CODE REVIEW

**Comment by michaelklishin** [comment]
@aygalinc it now complains about a CVE in `System.Text.Json` https://github.com/advisories/GHSA-8g4q-xg66-9fp4. Feel free to bump that library, too, since it is the same fundamental problem that now breaks builds on Windows.

**Comment by aygalinc** [comment]
@michaelklishin Weird that the build fail by resolving a system text json lib in version 6 => if you have drop net6 in favor of net8 what can cause this ? 
I work on macos so i cannot reproduce on my local env

**Comment by michaelklishin** [comment]
@aygalinc I am not sure what in the Windows environment might have caused this. Possibly dependency lock file caching of sorts? We'll have to wait until @lukebakken comes back next week.

**Comment by Tornhoof** [comment]
The package should only be relevant for .NET 4.6.1 targets, not the new one (similar to S.T.J).
See https://devblogs.microsoft.com/nuget/nugetaudit-2-0-elevating-security-and-trust-in-package-management/#system.net.http-and-system.text.regularexpressions

**Review by lukebakken — APPROVED** [review]
Test failures are not related to these changes. Thanks!

**Pull request merged**
