### PR TITLE
Support OAuth2 authentication

### LINKED ISSUE #956: Support credential refresh for OAuth 2/JWT authentication scenarios
Modern RabbitMQ versions support OAuth 2/JWT token authentication.

In practical terms this means that on the client side, a JWT token has to be provided in the password field. The username will be ignored (all relevant information will be taken from the decoded token).
You can make such a connection today, there's nothing to change in the client.

However, JWT tokens have limited shelf life. When they expire, no operations performed by a client will be accepted as token validation will fail. Since the protocols RabbitMQ supports assume long lived connections, there has to be a refresh mechanism. OAuth 2 clients have a different token, called the refresh token, that can be used to obtain a new JWT token with a refreshed expiration period.

In the Java client, `CredentialsProvider` is an interface that allows for the end user to provide a "refresh function" that, in the case of OAuth 2, will use a suitable OAuth 2 vendor client library and a refresh token to produce a new token and replace it on a connection. `connection.update-secret` is a new protocol extension for AMQP 0-9-1 that makes it possible
to update the token for an already open connection.

The `connection.update-secret` protocol method is [already supported](https://github.com/rabbitmq/rabbitmq-dotnet-client/blob/b3e7a1470b43954003291d39930672b52f3cf743/projects/RabbitMQ.Client/client/framing/ConnectionUpdateSecret.cs) in this client and can be used manually. However, this is somewhat inconvenient since the timing of updates is then up to the application developers.

This client needs its own version of a `CredentialsProvider` (possibly under a different name, since in the .NET world this may be an overloaded term) which is a pluggable abstraction that is expected to do a few things

 * Accepts an operation that the user provides to update the secret (JWT token) using any library or means necessary (such as a refresh token)
 * Update connection state to use the newly returned secret
 * Issues a `connection.update-secret` operation on the connection to update the secret on the server end

### PR DESCRIPTION
**Pull request by MarcialRosales**
Fixes #956

## Proposed Changes

Enable the following mechanisms via two attributes added to the ConnectionFactory:
- Obtain Basic Credentials (this means username+password or Oauth2 tokens) via the interface ICredentialsProvider
- In case of OAuth2 credentials, which they have a validity period, refresh the tokens before they expire. 

This PR is accompanied by another [PR](https://github.com/rabbitmq/rabbitmq-website/pull/1652) on the rabbitmq-website to update the .Net Client guide. 

### Acceptance Tests
Via TestApplications/OAuth2, it is possible to test end-to-end the following flows:
- Initial token request and connection establishment with the token (using standard connection)
- refresh the token via the token request. This is tested with keycloak
- refresh the token by requesting a new one. This is tested with uaa
- Specify extra parameters to be included when requesting a token such as `scope`. 

To do:
- Test using TLS with the authorization server

## Types of Changes

What types of changes does your code introduce to this project?
_Put an `x` in the boxes that apply_

- [ ] Bug fix (non-breaking change which fixes issue #NNNN)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause an observable behavior change in existing systems)
- [ ] Documentation improvements (corrections, new content, etc)
- [ ] Cosmetic change (whitespace, formatting, etc)

This PR is accompanied by another docs' [PR](https://github.com/rabbitmq/rabbitmq-website/pull/1652)

### CODE REVIEW

**Comment by jonproch117** [comment]
Is this feature still planned to be released? The associated changes to the website [here](https://www.rabbitmq.com/dotnet-api-guide.html#oauth2-support) from [this PR](https://github.com/rabbitmq/rabbitmq-website/pull/1652) were published, which threw me off since the referenced classes/properties don't yet exist in the library.

Thanks!

**Comment by lukebakken** [comment]
@jonproch117 - I'm working on reviewing this PR now. I should be able to get it released by the end of August. Sorry about the confusion!

**Review by lukebakken — CHANGES_REQUESTED** [review]
Thanks for all of your excellent work, @MarcialRosales 

I am going to move `IOAuth2Client` and related classes to their own project (and thus `dll` that is published to NuGet). The reason being that only a fraction of the users of the .NET client will need the OAuth2 code, and most will not want to have the extra dependencies on `System.Net.Http.Json` and `System.Text.Json`.

I'll start work on that tomorrow!

**Comment by MarcialRosales** [comment]
Excellent @lukebakken ! Good call on splitting that dependency. We just need to make it clear in the documentation to include this extra DLL when using OAuth2 authentication/authorization. Shall I create that doc's PR or will you do it?

**Comment by lukebakken** [comment]
> We just need to make it clear in the documentation to include this extra DLL when using OAuth2 authentication/authorization. Shall I create that doc's PR or will you do it?

Go right ahead. I think it should be pretty clear to end-users but best to make it as obvious as possible.

**Review by lukebakken — APPROVED** [review]
@MarcialRosales before merging, would you please review my changes? If you would run through your test scenarios in your env one more time I would appreciate it as well. Thanks!

**Comment by lukebakken** [comment]
@jonproch117 - if you'd like to test this out, please see the following beta releases:
* https://www.nuget.org/packages/RabbitMQ.Client.OAuth2/1.0.0-beta.0
* https://www.nuget.org/packages/RabbitMQ.Client/6.6.0-beta.0

I'm working on documentation at this time. You can see an example of how to use the new library via our test code here:

https://github.com/rabbitmq/rabbitmq-dotnet-client/tree/6.x/projects/TestApplications/OAuth2

**Comment by jonproch117** [comment]
@lukebakken This is working for me. Thanks!

**Pull request merged**
