### PR TITLE
Generate more readable code in ApiGen

### PR DESCRIPTION
**Pull request by stebet**
##  Proposed Changes

Generating more readable code in ApiGen to make debugging easier.

* Generating constants for ClassId and MethodId values for easier referencing in generated code.
* Generating more readable and more optimized switch statements in generated code using new constants
* Reducing dependency on direct MethodBase references and use the newly generated constants instead.

## Types of Changes

- [ ] Bug fix (non-breaking change which fixes issue #NNNN)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause an observable behavior change in existing systems)
- [ ] Documentation improvements (corrections, new content, etc)
- [X] Cosmetic change (whitespace, formatting, etc)

## Checklist

- [X] I have read the `CONTRIBUTING.md` document
- [X] I have signed the CA (see https://cla.pivotal.io/sign/rabbitmq)
- [X] All tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in related repositories

### CODE REVIEW

**Comment by stebet** [comment]
Tagging @bording for an extra pair of eyes :)

**Comment by lukebakken** [comment]
Looks good to me, but going to see if @bording has an opinion!

**Comment by bording** [comment]
I'm about to get on a plane for a weekend trip, so I won't be able to look at it until I get back next week.

**Comment by michaelklishin** [comment]
I think this is a pretty safe internal change so we can optimistically merge it (I know, famous last words).

**Comment by bording** [comment]
I see that this has already been merged, but it would be nice to see a diff of the before/after of the generated code with these changes.

**Comment by stebet** [comment]
I'll put up a gist with the diff soon.

**Comment by stebet** [comment]
Here is a diff for those specific changes, since then there have been made more improvements that we can diff as well: https://www.diffchecker.com/1Uqey2Gz

**Pull request merged**
