### PR TITLE
Added WinRT (Windows 8) compatible library, sharing code where possible.

### PR DESCRIPTION
**Pull request by ngbrown**
Includes NUnit driven tests.
Includes Windows Store example application.
Includes netcore45 addition to NuGet nuspec file.
Addresses GitHub issue #16.

The work I did toward #32 with a public CI ran into some troubles with WinRT Tasks usage and the single CPU test environment.  Some unit tests work fine on multi-processor environment, but deadlock on a single CPU core environment (can be simulated with CPU affinity).  I think by pushing this to the main branch, more people can work on this and it can be figured out.

### CODE REVIEW

**Comment by michaelklishin** [comment]
Thank you.

I've noticed that on my development machine (Windows 8.1), the location of `Microsoft.Windows.UI.Xaml.CSharp.targets` is different: it is

```
$(MSBuildExtensionsPath)\Microsoft\WindowsXaml\v12.0\Microsoft.Windows.UI.Xaml.CSharp.targets
```

instead of

```
$(MSBuildExtensionsPath)\Microsoft\WindowsXaml\v11.0\Microsoft.Windows.UI.Xaml.CSharp.targets
```

I'll update the project file for 8.1/VS 2013 CE but we may want to investigate making this work on different versions.

**Comment by michaelklishin** [comment]
This clearly wasn't tested on Mono. Fails to build because build files in the WinRT projects have no conditions.

**Comment by ngbrown** [comment]
Since it is a non-gui library, there's not a lot of benefit to target netcore451 (win 8.1). This current way it is compatible with both 8 and 8.1.

There is an option in the Visual Studio 2013 installer to install the libraries and tools to maintain Windows 8 apps. You will need to run the installer in maintenance mode and check it.

If the library is upgraded, then the nuspec file needs changed as well.

**Comment by michaelklishin** [comment]
Yes, I now see that VS needs to install some additional tools. Investigating.

**Comment by ngbrown** [comment]
I don't have a Linux or Mono environment and don't know what is needed.

**Comment by michaelklishin** [comment]
I'll take care of Mono. @ngbrown I've invited you to the .NET client contributors team. I'll soon close this PR and push a branch that has some project file modifications (primarily related to Mono).

We'll use that branch to make sure things build (or are skipped) in all our environments, then merge.

If you haven't already, please sign our [contributor agreement](https://github.com/rabbitmq/ca) document and send it to me.

**Comment by ngbrown** [comment]
You should have my signed contribution agreement on file. Let me know if I need to resend it.

**Comment by michaelklishin** [comment]
Perfect. Then I'll push a branch (`rabbitmq-dotnet-client-65`) shortly and close this PR. Once I tweak the build system to exclude WinRT from nightlies (our build machine is currently Win 7 and migrating to 8.1 will take some time) and build on Mono, we can merge this.

Thank you, this is a substantial contribution and easily one of the biggest bullet points for the 3.6.0 release notes.

**Comment by michaelklishin** [comment]
Closing in favour of #65.

**Pull request closed without merging**
