### PR TITLE
Add support for ulong header values

### PR DESCRIPTION
**Pull request by thepunkoff**
## Proposed Changes

I added support for having ulongs as header table values for convenience, since uints and ushorts support has already been added.

## Types of Changes

- [ ] Bug fix (non-breaking change which fixes issue #NNNN)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause an observable behavior change in existing systems)
- [ ] Documentation improvements (corrections, new content, etc)
- [ ] Cosmetic change (whitespace, formatting, etc)

## Checklist

- [x] I have read the `CONTRIBUTING.md` document
- [x] I have signed the CA (see https://cla.pivotal.io/sign/rabbitmq)
- [x] All tests pass locally with my changes
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in related repositories

## Further Comments
---

### CODE REVIEW

**Comment by thepunkoff** [comment]
The CI build failed, but I can't see the reasons why. It just sais "loading" forever.

**Review by lukebakken — CHANGES_REQUESTED** [review]
Thanks!

Build failure:

```
/tmp/build/b95f7b06/rabbitmq_dotnet_client/projects/Unit/TestFieldTableFormatting.cs(80,33): error CS1003: Syntax error, ',' expected [/tmp/build/b95f7b06/rabbitmq_dotnet_client/projects/Unit/Unit.csproj]
/tmp/build/b95f7b06/rabbitmq_dotnet_client/projects/Unit/TestFieldTableFormattingGeneric.cs(82,33): error CS1003: Syntax error, ',' expected [/tmp/build/b95f7b06/rabbitmq_dotnet_client/projects/Unit/Unit.csproj]
  Benchmarks -> /tmp/build/b95f7b06/rabbitmq_dotnet_client/projects/Benchmarks/bin/Debug/net472/Benchmarks.exe
/tmp/build/b95f7b06/rabbitmq_dotnet_client/projects/Unit/TestFieldTableFormatting.cs(80,33): error CS1003: Syntax error, ',' expected [/tmp/build/b95f7b06/rabbitmq_dotnet_client/projects/Unit/Unit.csproj]
/tmp/build/b95f7b06/rabbitmq_dotnet_client/projects/Unit/TestFieldTableFormattingGeneric.cs(82,33): error CS1003: Syntax error, ',' expected [/tmp/build/b95f7b06/rabbitmq_dotnet_client/projects/Unit/Unit.csproj]

Build FAILED.
```

I would fix this for you but I'm caught up in customer support!

**Comment by thepunkoff** [comment]
@lukebakken Thanks for helping! I fixed the build.

**Review by Zerpet — COMMENTED** [review]
Actions failed on formatting. Apart from that, this looks good to me. Thank you for your contribution!

**Comment by thepunkoff** [comment]
There's a flaky test failure, that prevents this from merging, but I'm not sure how to rerun the check.

**Comment by michaelklishin** [comment]
There is one test that fails only on Windows, and the client seemingly goes into a (reconnection) loop that never succeeds:

```
Testing heartbeats, sleeping for 60 seconds
  Passed RabbitMQ.Client.Unit.TestFloodPublishing.TestMultithreadFloodPublishing [170 ms]
   at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   at System.IO.BufferedStream.Read(Byte[] array, Int32 offset, Int32 count)
   at RabbitMQ.Client.Impl.InboundFrame.ReadFromStream(Stream reader, Byte[] buffer, Int32 toRead) in D:\a\rabbitmq-dotnet-client\rabbitmq-dotnet-client\projects\RabbitMQ.Client\client\impl\Frame.cs:line 318
   at RabbitMQ.Client.Impl.InboundFrame.ReadFrom(Stream reader, Byte[] frameHeaderBuffer, UInt32 maxMessageSize) in D:\a\rabbitmq-dotnet-client\rabbitmq-dotnet-client\projects\RabbitMQ.Client\client\impl\Frame.cs:line 268
   at RabbitMQ.Client.Impl.SocketFrameHandler.ReadFrame() in D:\a\rabbitmq-dotnet-client\rabbitmq-dotnet-client\projects\RabbitMQ.Client\client\impl\SocketFrameHandler.cs:line 243
   at RabbitMQ.Client.Framing.Impl.Connection.ReceiveLoop() in D:\a\rabbitmq-dotnet-client\rabbitmq-dotnet-client\projects\RabbitMQ.Client\client\impl\Connection.Receive.cs:line 73
   at RabbitMQ.Client.Framing.Impl.Connection.MainLoop() in D:\a\rabbitmq-dotnet-client\rabbitmq-dotnet-client\projects\RabbitMQ.Client\client\impl\Connection.Receive.cs:line 50
   at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   at System.IO.BufferedStream.Read(Byte[] array, Int32 offset, Int32 count)
   at RabbitMQ.Client.Impl.InboundFrame.ReadFromStream(Stream reader, Byte[] buffer, Int32 toRead) in D:\a\rabbitmq-dotnet-client\rabbitmq-dotnet-client\projects\RabbitMQ.Client\client\impl\Frame.cs:line 318
   at RabbitMQ.Client.Impl.InboundFrame.ReadFrom(Stream reader, Byte[] frameHeaderBuffer, UInt32 maxMessageSize) in D:\a\rabbitmq-dotnet-client\rabbitmq-dotnet-client\projects\RabbitMQ.Client\client\impl\Frame.cs:line 268
   at RabbitMQ.Client.Impl.SocketFrameHandler.ReadFrame() in D:\a\rabbitmq-dotnet-client\rabbitmq-dotnet-client\projects\RabbitMQ.Client\client\impl\SocketFrameHandler.cs:line 243
   at RabbitMQ.Client.Framing.Impl.Connection.ReceiveLoop() in D:\a\rabbitmq-dotnet-client\rabbitmq-dotnet-client\projects\RabbitMQ.Client\client\impl\Connection.Receive.cs:line 73
   at RabbitMQ.Client.Framing.Impl.Connection.MainLoop() in D:\a\rabbitmq-dotnet-client\rabbitmq-dotnet-client\projects\RabbitMQ.Client\client\impl\Connection.Receive.cs:line 50
   at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
```

Anyhow, it does not seem to be related to this PR in any way. The same test passes on Linux.

**Review by michaelklishin — APPROVED** [review]

**Review by lukebakken — CHANGES_REQUESTED** [review]
We should at least be compatible with Pika:

https://github.com/pika/pika/blob/main/pika/data.py#L256-L259

PS @thepunkoff thanks for your contribution. If you wouldn't mind making sure this change uses the same single-character as Pika, that would be great.

**Comment by thepunkoff** [comment]
@lukebakken Ok! I can see that pika uses `l` for unsigned 64-bit ints and `L` for signed 64-bit ints. On the other hand the dotnet client lib has been using `l` for signed ones instead - I'll swap them then to match pika's.

**Comment by michaelklishin** [comment]
@lukebakken @thepunkoff I don't mind using the same value as Pika but keep [this protocol errata in mind](https://www.rabbitmq.com/amqp-0-9-1-errata.html). I'd say we should use what the Java client uses and not Pika (in case there is a difference).

**Comment by thepunkoff** [comment]
@lukebakken Oh I see now... my bad! So my PR would remove disambiguity between 0-9-1 and RabbitMQ considering longs and ulongs.

However, the Java client currently [doesn't](https://github.com/rabbitmq/rabbitmq-java-client/blob/0f2a53eb4dd3fa0ad4075c7c870690f509c05d37/src/main/java/com/rabbitmq/client/impl/ValueReader.java#L198) jupport ulongs either. Should I update it as well?

**Comment by thepunkoff** [comment]
Oops, sorry for messing up commits 😅

**Comment by michaelklishin** [comment]
@thepunkoff we would appreciate support for the same type in the Java client, of course. To me it appears that Pika uses `l` as in the original AMQP 0-9-1 spec and not what RabbitMQ and Qpid have adopted.

So both this client and the Java one should the same value, what the RabbitMQ server uses.

**Comment by thepunkoff** [comment]
Just to clarify. Does the RabbitMQ server _use_ header values as opposed to just passing them along to the consumer to be interpreted by the application? If the server _expects_ values in an exact format, then is it even ok to change anything on the client libraries' side? Should the server be patched to support this, too? How would the server react to such rearrangements in clients?

Considering the errata document. It is stated that there are incompatibilities between amqp 0-9-1 and rmq, I can see those. So does this mean that amqp 0-9-1 clients are not compatible with rmq, and rmq clients are not compatible with 0-9-1-compliant servers? How should I interpret this document? As a todo list or as a rule to follow? Not quite sure yet. Would be glad if y'all clarified it to me :)

**Comment by lukebakken** [comment]
Generally I don't think RabbitMQ looks at message headers.

Here's where the Java client translates the codes to values:

https://github.com/rabbitmq/rabbitmq-java-client/blob/main/src/main/java/com/rabbitmq/client/impl/ValueReader.java#L157-L221

**Comment by thepunkoff** [comment]
@lukebakken Here's a quote from the [errata doc](https://www.rabbitmq.com/amqp-0-9-1-errata.html#:~:text=RabbitMQ%20continues%20to%20use%20the%20tags%20in%20the%20third%20column.):
> RabbitMQ continues to use the tags in the third column.

This actually says the type characters are *used*. If they're not, and the information is obsolete, then great.

Do you think these field type specifiers in this client should fully conform to the 0-9-1 spec ([p. 31-32](https://www.rabbitmq.com/resources/specs/amqp0-9-1.pdf))? I could make sure they do in this PR, and then update the Java client accordingly. But this should be subsequently done in all the known client libraries.

Also, if an updated client uses new type specifiers, the non-updated clients will be mislead, as e.g. long values in the headers from the updated client would start to use 'L' instead of 'l'.

**Comment by Zerpet** [comment]
> @thepunkoff we would appreciate support for the same type in the Java client, of course. To me it appears that Pika uses `l` as in the original AMQP 0-9-1 spec and not what RabbitMQ and Qpid have adopted.
> 
> So both this client and the Java one should the same value, what the RabbitMQ server uses.

I agree, we should adapt the clients to use what RabbitMQ server uses. At the end of the day, these clients are _rabbitmq_ clients, not pure AMQP 0.9.1 clients.

The Go client seems to follow the same criteria as Java and Pika:

https://github.com/rabbitmq/amqp091-go/blob/5656876376f5139fc349ea903eede73682eff738/read.go#L142-L254

**Comment by michaelklishin** [comment]
We definitely won't update all clients to use the ambiguous values from the original spec (that were never clarified).

**Comment by lukebakken** [comment]
Here's where `L` and `l` are used in RabbitMQ:
https://github.com/rabbitmq/rabbitmq-server/blob/main/deps/rabbit_common/src/rabbit_binary_parser.erl#L62-L67

**Comment by Zerpet** [comment]
> Should we give up on the idea and document the decision in the issue?

Sounds good to me. I think we should just not have support for unsigned 64-bit integers. 

The alternative would be to accept `ulong` types and encode them, doesn't really matter how i.e. `l` or `L`, and let the server interpret them as signed longs. This feels counter-intuitive and could lead to potentially obscure issues. I'd rather just not support them.

**Comment by thepunkoff** [comment]
Sounds ok to me, too. Just a shame that uints, ushorts and sbytes are already supported, and this all can't be pretty :)

Also, as I can see, at least two clients for languages, that don't have unsigned types (and signed bytes), already will raise an error if they see unsupported values while decoding. Notice the absence of cases for ('u', 'i' ,'b'):

- [Ruby](https://github.com/ruby-amqp/amq-protocol/blob/master/lib/amq/protocol/table_value_decoder.rb#L32)
- [JavaScript](https://github.com/amqp-node/amqplib/blob/4993dee433665e9e6fe7729f3eaeacca06b46cb7/lib/codec.js#L236)

So the dotnet client can already crash some other clients with these types.

**Pull request closed without merging**
