### PR TITLE
Typo in Extension class name

### PR DESCRIPTION
**Pull request by JeremyMahieu**
## Proposed Changes

Rename IModelExsentions to IModelExtensions like the filename and the correct spelling.

## Types of Changes

What types of changes does your code introduce to this project?
_Put an `x` in the boxes that apply_

- [ ] Bug fix (non-breaking change which fixes issue #NNNN)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause an observable behavior change in existing systems)
- [ ] Documentation improvements (corrections, new content, etc)
- [x] Cosmetic change (whitespace, formatting, etc)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating
the PR. If you're unsure about any of them, don't hesitate to ask on the
mailing list. We're here to help! This is simply a reminder of what we are
going to look for before merging your code._

- [x] I have read the `CONTRIBUTING.md` document
- [x] I have signed the CA (see https://cla.pivotal.io/sign/rabbitmq)
- [x] All tests pass locally with my changes
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)
- [x] Any dependent changes have been merged and published in related repositories

### CODE REVIEW

**Review by michaelklishin — APPROVED** [review]
Curiously this does not affect the `APIApprovals` test 👍

**Comment by AStove** [comment]
> Curiously this does not affect the `APIApprovals` test 👍

Because I updated the APIApproval.Approve.verified.txt

**Comment by michaelklishin** [comment]
@AStove ah, I see what the name of the second file is now, thanks 😅 This can only go into `7.0` as it technically it is a breaking public API change.

**Comment by lukebakken** [comment]
My vote is that this should be in 6.2 as it is a bug, even though it's a breaking change. @bording ?

**Comment by bording** [comment]
So this is interesting because this class is for holding extension methods. That means people are unlikely to be directly referencing the class in their code, so fixing it is not likely to be a compile-time break.

However it would be a binary breaking change, so existing assemblies would break at runtime with this fix in place.

I vote for keeping this in 7.0.0 only since it does have the potential break people, and they likely can't see the typo in their code in the first place.

**Comment by lukebakken** [comment]
OK!

**Pull request merged**
