### PR TITLE
Rabbitmq dotnet client crl

### PR DESCRIPTION
**Pull request by mrbluejz**
Cherry picked commit ab974abb22678cc68ee2176cb669b937de392b6b.

This should be verified in order to create a version that will include the security enhancement for checking the certificate with the certificate revocation list.

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@mrbluejz Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/rabbitmq?repositoryId=rabbitmq/rabbitmq-dotnet-client&pullRequestId=678)!

[Click here](https://cla.pivotal.io/sync/rabbitmq?repositoryId=rabbitmq/rabbitmq-dotnet-client&pullRequestId=678) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@mrbluejz Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/rabbitmq?repositoryId=rabbitmq/rabbitmq-dotnet-client&pullRequestId=678)!

**Comment by michaelklishin** [comment]
If the goal is to cherry-pick https://github.com/rabbitmq/rabbitmq-dotnet-client/commit/ab974abb22678cc68ee2176cb669b937de392b6b to `5.x` then we cannot do it as it is a breaking public API change.

**Comment by mrbluejz** [comment]
I really need this change in a verified version.
Is there a release date for version 6.0 ?

**Comment by michaelklishin** [comment]
We can produce an RC later this week.

**Comment by mrbluejz** [comment]
Thanks

**Comment by michaelklishin** [comment]
[6.0.0-rc.1](https://www.nuget.org/packages/RabbitMQ.Client/6.0.0-rc1) is up on NuGet.

**Comment by mrbluejz** [comment]
Thanks ! 
Question:
What's the difference between the RC and the future to be released version?

**Comment by michaelklishin** [comment]
An RC is, well, a release candidate. There can be more changes after it before GA but usually not many, or any at all. An RC is something you test and provide feedback on ;)

**Pull request closed without merging**
