### PR TITLE
allow to publish array segments instead of full byte arrays

### PR DESCRIPTION
**Pull request by zgabi**
## Proposed Changes

IModel.BasicPublish currently accepts only a byte array, so the library user usually needs to copy the data to a new byte array which has the required length. It is a quite big overhead and also needs more garbage collection.

This PR adds a new BasicPublish method to the IModel interface which accepts an offset and count parameters (like .NET's Stream write, etc)

## Types of Changes

What types of changes does your code introduce to this project?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes issue #NNNN)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation (correction or otherwise)
- [ ] Cosmetics (whitespace, appearance)

## Checklist

- [x] I have read the `CONTRIBUTING.md` document
- [x] I have signed the CA (see https://cla.pivotal.io/sign/rabbitmq)
- [ ] All tests pass locally with my changes
I can see some exceptions when I run run-test.bat, but they are not releated to my change. I've set RABBITMQ_RABBITMQCLT_PATH but still complains.
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in related repositories

### CODE REVIEW

**Comment by michaelklishin** [comment]
Also, as with all efficiency improvements it would be nice to see some benchmarks and what kind of difference does using this new method bring. "Quite a big overhead" is not something that our team can quantify.

**Comment by lukebakken** [comment]
> the library user usually needs to copy the data to a new byte array which has the required length

Hmm users use serialization classes and / or `ToByteArray` methods almost all of the time. I'm not sure what specific use-case this addresses.

**Comment by bording** [comment]
> Hmm users use serialization classes and / or ToByteArray methods almost all of the time. I'm not sure what specific use-case this addresses.

That touches on the larger issue, in that `ArraySegment` is a rather difficult type to use. It was never plumbed through all of the BCL APIs that you'd want to actually be able to use it easily.

On the other hand, `Span<T>` / `Memory<T>` have gotten that additional support (on .NET Core only at the moment), so moving to using those is a much more interesting proposition.

**Comment by zgabi** [comment]
Yes, the best would be to use Span/ReadOnlySpan, but it is not available in .NET framework.
By the way, ArraySegment is only in the internal methods, the public interface is accepting offset and count as other .NET Stream methods.

**Comment by zgabi** [comment]
And one more thing, @Pliner 's change is reduces the allocation inside RabbitMQ client. In my case the extra allocation is in the caller's code, so it is not an alternative, both can/should be applied.

Or as you mentioned, it can use Spans (for BasicPublish I think it should be ReadOnlySpan), it would solve my issue, too, but it is a bigger breaking change.

**Comment by michaelklishin** [comment]
We have been doing breaking changes in master for 6.0 for over a month now. The only question here is, what .NET versions can we support with that kind of API.

**Comment by bording** [comment]
> We have been doing breaking changes in master for 6.0 for over a month now. The only question here is, what .NET versions can we support with that kind of API.

While the `Span` and `Memory` types are available for older versions of the .NET Framework via the System.Memory package, `Span` on the .NET Framework is the "slow" version that doesn't work as well because it requires CLR changes that are only in .NET Core.

You also don't get all of the BCL overloads that take `Span`/`Memory` on the .NET Framework yet.

So, while switching to `Span` would be the best option from an efficiency standpoint, realistically, doing that means you're running on .NET Core 2.1 and up only.

**Comment by michaelklishin** [comment]
@bording thank you for the insightful response. We should file a new issue about a `Span`/`Memory` overload for a future version (which would admittedly be a couple of years away).

Let's wait for the numbers before we make the call on this change.

**Comment by zgabi** [comment]
Just found an already exiintg issue for this PR: https://github.com/rabbitmq/rabbitmq-dotnet-client/issues/303

But as you wrote `ArraySegment` is not so nice, For spans we have to wait "couple of years", I think offset + length is the best solution currently which is also widely available in .NET framework.

I'd be happy to modify this PC according your preferences, just let me know what interface parameter changes would you accept.

If you prefer I can change the internal `ArraySements` parameters to offset+length, too, but it needs a smaller change in the `Apigen` class too, since the body parameter now has a `AmqpContentBodyMapping` attribute, and similar attributes will be needed for the offset and length.

**Comment by kjnilsson** [comment]
I don't mind the changes to the public api (BasicPublish) and I think they could be useful for a small number of users. The problem as I see it is that the internals now expect an array segment which means that the common case (where a user provides and wants to send a full buffer) requires an ArraySegment to be created. I don't know if .NET does something special in this case but this seems like an unnecessary object allocation?

I'd like to see the PR cut down as @zgabi suggests to allow users to specify offset and length instead and also mirror that internally. That should satisfy the the users that want to avoid copying.

**Comment by zgabi** [comment]
`ArraySegment` is not a class, so it is not an unnecessary object allocation.

So is it ok for everybody if I add offset and length everywhere?

By the way, in this case I think this method could be changed, too:
https://github.com/rabbitmq/rabbitmq-dotnet-client/blob/646c289d90eac435f6902381792015e06f49708a/projects/client/RabbitMQ.Client/src/client/impl/ExtensionMethods.cs#L68

Return only the byte[], the length is always ms.Position anyway. With this change all existing `ArraySegment` reference will be removed from RabbitMQ client.

**Comment by michaelklishin** [comment]
@zgabi not sure what you mean by "everywhere" but it is not OK to modify existing methods. I don't think this user-specific API should be driving the implementation either.

**Comment by zgabi** [comment]
Eveywhere = where I added `ArraySegment` I'll add `int offset` and `int count` instead of changing the `byte[]` to `ArraySegment`.

**Comment by michaelklishin** [comment]
I'm afraid the consensus (or lack thereof) around this PR is: we are not convinced such use case-specific changes should be accepted to the API. We are open to being convinced otherwise but there hasn't been much activity => closing.

Thank you for taking the time, @zgabi!

**Pull request closed without merging**
