### PR TITLE
Allocation improvements

### PR DESCRIPTION
**Pull request by Anarh2404**
## Proposed Changes
Ported some changes from the #734 
Made ContantHeader and Method readers/writers structs

## Types of Changes

- [ ] Bug fix (non-breaking change which fixes issue #NNNN)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause an observable behavior change in existing systems)
- [ ] Documentation improvements (corrections, new content, etc)
- [x] Cosmetic change (whitespace, formatting, etc)

## Checklist

- [x] I have read the `CONTRIBUTING.md` document
- [x] I have signed the CA (see https://cla.pivotal.io/sign/rabbitmq)
- [x] All tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in related repositories

## Further Comments

Before
before
After
after

### CODE REVIEW

**Comment by michaelklishin** [comment]
@Anarh2404 thank you. Now that #732 is in, are we expected to merge this PR next or there can be some overlap/competition with #706? We really could use some guidance as while all these allocation improvement PRs are appreciated, they tend to compete and not collaborate. We would really appreciate a single unified effort from you and @stebet instead of competing PRs.

**Comment by Anarh2404** [comment]
@michaelklishin this PR complements #732 and does not compete with #706

**Comment by michaelklishin** [comment]
Great, thanks for clarifying.

**Comment by stebet** [comment]
Looks good to me :)

**Pull request merged**
