### PR TITLE
Drop `immediate` flag

### LINKED ISSUE #98: Drop immediate flag
It isn't supported as of RabbitMQ 3.0 and was removed in many other clients.

### PR DESCRIPTION
**Pull request by Pliner**
Hi @michaelklishin,

It's an attempt to drop immediate flag and fix #98. I hope everything is fine :)

### CODE REVIEW

**Comment by michaelklishin** [comment]
Thanks Yury, I will take a look tonight.

**Comment by michaelklishin** [comment]
Thank you!

If you are looking for more straightforward issues you can help with, #13, #56, #80 are good candidates. Any help we can get on #32 and #91 would be greatly appreciated as well :)

**Comment by Pliner** [comment]
Thank you too :)
 
The only reason I choose simple issues is absense of time to dive into codebase :( Do you have any progress with #94?

**Comment by michaelklishin** [comment]
Haven't even started on #94 and won't for a while. I will update that issue.

**Pull request merged**
