### PR TITLE
Removed deprecated QueueingBasicConsumer and IQueueingBasicConsumer.

### LINKED ISSUE #468: Remove deprecated QueueingBasicConsumer
Remove deprecated `QueueingBasicConsumer` and `IQueueingBasicConsumer`.

### PR DESCRIPTION
**Pull request by paulomorgado**
## Proposed Changes

Remove deprecated `QueueingBasicConsumer` and `IQueueingBasicConsumer`.

Fixes #468 

## Types of Changes

- [ ] Bugfix (non-breaking change which fixes issue #NNNN)
- [ ] New feature (non-breaking change which adds functionality)
- [X] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation (correction or otherwise)
- [ ] Cosmetics (whitespace, appearance)

## Checklist

- [X] I have read the `CONTRIBUTING.md` document
- [X] I have signed the CA (see https://cla.pivotal.io/sign/rabbitmq)
- [ ] All tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in related repositories

### CODE REVIEW

**Comment by kjnilsson** [comment]
thanks, All tests that use this class need to be updated to use the EventingBasicConsumer instead.

**Comment by paulomorgado** [comment]
Done!

**Comment by paulomorgado** [comment]
The `TestRecoverAfterCancel_` might be hung. Can someone help out here?

**Comment by michaelklishin** [comment]
@paulomorgado see [RUNNING_TESTS.md](https://github.com/rabbitmq/rabbitmq-dotnet-client/blob/master/RUNNING_TESTS.md). Recovery tests use `rabbitmqctl` to effectively restart RabbitMQ (without restarting its Erlang VM), which may be taken from a relative location (our team usees the umbrella repo for development).

**Comment by paulomorgado** [comment]
Well, the appveyor build finally finished and with success.

But someone more experienced than me with RabbitMQ should look at the changed tests to see if `QueueingBasicConsumer` has been correctly replaced by `EventingBasicConsumer`.

**Comment by michaelklishin** [comment]
Thank you!

**Pull request merged**
