### PR TITLE
Use TimeSpan.TotalMilliseconds on Windows RT

### PR DESCRIPTION
**Pull request by WinstonSmith77**
Reads Milliseconds; Must read TotalMilliseconds

### CODE REVIEW

**Comment by michaelklishin** [comment]
That's a bit terse. Can we state clearly what the bug is? Is it that instead of a total time span only its milliseconds part was returned? (then it's pretty unfortunate naming compared e.g. to JodaTime).

**Comment by kjnilsson** [comment]
TimeSpan.Milliseconds returns only the millisecond component. I bet this isn't the only time this naming has caused a bug. I will reword and merge this commit.

https://msdn.microsoft.com/en-us/library/system.timespan.milliseconds(v=vs.110).aspx

**Comment by kjnilsson** [comment]
ok this has been reworded and cherry-picked into the stable branch, Thank you @WinstonSmith77

**Comment by michaelklishin** [comment]
Thank you, @WinstonSmith77.

**Comment by WinstonSmith77** [comment]
Thank you for your quick response. Will there be an updated NuGet anytime soon?

**Comment by kjnilsson** [comment]
The .NET client releases are in step with broker releases. This fix will be
included in the next release (3.6.3) but I don't have a date for when that
will be.

**Comment by michaelklishin** [comment]
@WinstonSmith77 we expect 3.6.3 to be available within a month. FWIW it will be in nightly builds in case you have reasons to not build from source.

**Pull request closed without merging**
