### PR TITLE
add size hint variable for PublishBatch creation

### PR DESCRIPTION
**Pull request by bollhals**
## Proposed Changes

add a new method with a size hint for the creation of the list to hold the commands. This can reduce the allocations due to the storage of the commands by half. 

## Types of Changes

- [ ] Bug fix (non-breaking change which fixes issue #NNNN)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause an observable behavior change in existing systems)
- [ ] Documentation improvements (corrections, new content, etc)
- [ ] Cosmetic change (whitespace, formatting, etc)

## Checklist

- [x] I have read the `CONTRIBUTING.md` document
- [x] I have signed the CA (see https://cla.pivotal.io/sign/rabbitmq)
- [ ] All tests pass locally with my changes
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in related repositories

## Further Comments

This only adds a new overloaded method to the public IModel interface.

### CODE REVIEW

**Comment by bollhals** [comment]
In the test app of stebet, before:
image

after
image

**Comment by michaelklishin** [comment]
I updated `APIApproval` expectations. Thank you for your ongoing contributions @bollhals! 🥇

**Comment by michaelklishin** [comment]
Backported to `6.x`.

**Comment by bording** [comment]
@michaelklishin This is a breaking change, so it should not have been backported to the `6.x` branch.

**Comment by stebet** [comment]
Is there also a good reason to have interfaces for the basics like IConnection, IModel etc.? Don't really see a reason why anyone would go through the trouble of implementing their own version of those.

**Comment by bording** [comment]
> Is there also a good reason to have interfaces for the basics like IConnection, IModel etc.? Don't really see a reason why anyone would go through the trouble of implementing their own version of those.

When I see interfaces used like that, it's usually an attempt to make testing easier since you can provide fake testing implementations.

**Comment by michaelklishin** [comment]
I'm not going to lie it is seriously annoying to me that we cannot ship new small features like this quickly in this client because of the adopted semantic versioning interpretation.

There is so much code out there that uses interfaces that removing them seems unrealistic.

**Comment by michaelklishin** [comment]
I suggest then that we only release new majors and patch releases, no minors. Minors make no sense in the world of strict semantic versioning: even small features often require some kind of interface changes, even minor usability improvements can be interpreted as breaking behavior changes. If almost no change is appropriate for a minor release, why bother with them at all?

**Comment by rwkarg** [comment]
> Is there also a good reason to have interfaces for the basics like IConnection, IModel etc.? Don't really see a reason why anyone would go through the trouble of implementing their own version of those.

For context, we have a SharedPublishConnection and a SharedConsumerConnection implementation of IConnection that we use to enforce that publish and subscribe happen on separate connections/sockets (to avoid TCP backpressure on consumers in case of backlogs) as well as to enforce a single publisher and single consumer connection per endpoint/connection config (to avoid unnecessary TCP connections).

**Pull request merged**
