### PR TITLE
Make BasicPublishBatch work with ReadOnlyMemory<byte>

### PR DESCRIPTION
**Pull request by Samuron**
Hi guys!

Thank you for revamping the API of the client to use new primitives. I've found that BasicPublishBatch still uses byte[] for payload and found it inconsistent. 

This is breaking change on the binary level AFAIU, but it should be compatible on recompile due to implicit conversions. 

Not sure how it should be handled, feel free to close the PR.

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@Samuron Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/rabbitmq?repositoryId=rabbitmq/rabbitmq-dotnet-client&pullRequestId=816)!

[Click here](https://cla.pivotal.io/sync/rabbitmq?repositoryId=rabbitmq/rabbitmq-dotnet-client&pullRequestId=816) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@Samuron Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/rabbitmq?repositoryId=rabbitmq/rabbitmq-dotnet-client&pullRequestId=816)!

**Comment by michaelklishin** [comment]
I remember @bording or @stebet mentioned that there is an implicit conversion between those types. If that's the case, do we need this change at all? If not, this kind of change can only go into 7.0 as it changes a method signature?

Also highly relevant: #788.

**Comment by michaelklishin** [comment]
Sorry, I now see the difference here from #788: this updates the batch publishing API.

**Comment by lukebakken** [comment]
Yes, if accepted, this must be a `7.0` feature. It would have been nice to get this into `6.0` 🤷

**Comment by danielmarbach** [comment]
An alternative non-breaking extension to support BasicPublishBatch https://github.com/rabbitmq/rabbitmq-dotnet-client/pull/865. This could be added in `6.2`

**Comment by danielmarbach** [comment]
The alternative has been merged. Closing

**Pull request closed without merging**
