### PR TITLE
Add a missing constant for NO_ROUTE

### LINKED ISSUE #1331: Unknown reply code 312
### Describe the bug

When I call the following code with invalid (non existing queue) `routingKey`
```
                channel.BasicPublish(
                    exchange: _exchange,
                    routingKey: _key,
                    basicProperties: null,
                    mandatory: true,
                    body: message.Payload);
```

I get code `312` in `BasicReturn` event handler's `args.ReplyCode` and "NO_ROUTE" as a message. There is no such code in `RabbitMQ.Client.Constants` class, the closest is `RabbitMQ.Client.Constants.NoConsumers` which is `313`.

### Reproduction steps

Use .NET RabbitMQ.Client nuget version 6.5.0
Use `IModel.BasicPublish()` and subscribe to `IModel.BasicReturn` event handler
See `312` reply code when the handler is triggered

### Expected behavior

`313` reply code so I can use `RabbitMQ.Client.Constants.NoConsumers` in my tests

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by michaelklishin**
Closes #1331

### CODE REVIEW

**Comment by lukebakken** [comment]
Does this _require_ `6.6.0` or is `6.5.1` OK?

**Comment by michaelklishin** [comment]
Adding a constant should not *require* 6.6.0.

**Review by Zerpet — APPROVED** [review]

**Comment by Zerpet** [comment]
I agree we can ship this in a patch release. Concourse seems unhappy about a missing input for RabbitMQ server. Since the build is passing fine in actions, and I'm confident that adding a constant did not break existing code, I'm going to merge bypassing branch protection.

**Comment by Zerpet** [comment]
This was merged to `main`, I'll backport for `6.x` branch.

**Pull request merged**
