### PR TITLE
avoid string concatenation

### PR DESCRIPTION
**Pull request by paulomorgado**
## Proposed Changes

String concatenations are bad because they incur in memory allocations.

Using `string.Format` (directly or through string interpolation) uses cached `StringBuilder`s thus avoiding allocations. 

## Types of Changes

- [ ] Bugfix (non-breaking change which fixes issue #NNNN)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation (correction or otherwise)
- [ ] Cosmetics (whitespace, appearance)

## Checklist

- [x] I have read the `CONTRIBUTING.md` document
- [x] I have signed the CA (see https://cla.pivotal.io/sign/rabbitmq)
- [ ] All tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in related repositories

### CODE REVIEW

**Comment by michaelklishin** [comment]
Thank you. All the changes seem to be off the hot code path, however, so I'd not expect any significant gains from this.

**Comment by paulomorgado** [comment]
OOPS! Fixed!

**Comment by paulomorgado** [comment]
I've been away for a few days. Any update on this?

**Comment by michaelklishin** [comment]
It still does not compile for me:

```
git show-ref HEAD
f05ab6eb26b018097c1b7af3eaf41dd0982c6d1b refs/remotes/origin/HEAD
```

```
./build.sh
  Restore completed in 15.88 ms for /Users/antares/Development/RabbitMQ/umbrella.git/deps/rabbitmq_dotnet_client/projects/client/Unit.WinRT/Unit.WinRT.csproj.
/Users/antares/Development/RabbitMQ/umbrella.git/deps/rabbitmq_dotnet_client/projects/client/Apigen/Apigen.csproj : warning NU1701: Package 'System.Xml.XPath.XmlDocument 4.0.0' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETCoreApp,Version=v2.0'. This package may not be fully compatible with your project. [/Users/antares/Development/RabbitMQ/umbrella.git/deps/rabbitmq_dotnet_client/RabbitMQDotNetClient.sln]
  Restore completed in 24.75 ms for /Users/antares/Development/RabbitMQ/umbrella.git/deps/rabbitmq_dotnet_client/projects/client/ApigenBootstrap/ApigenBootstrap.csproj.
  Restore completed in 24.81 ms for /Users/antares/Development/RabbitMQ/umbrella.git/deps/rabbitmq_dotnet_client/projects/client/Apigen/Apigen.csproj.
  Restore completed in 25.44 ms for /Users/antares/Development/RabbitMQ/umbrella.git/deps/rabbitmq_dotnet_client/projects/client/RabbitMQ.Client/RabbitMQ.Client.csproj.
  Restore completed in 26.53 ms for /Users/antares/Development/RabbitMQ/umbrella.git/deps/rabbitmq_dotnet_client/projects/client/Unit/Unit.csproj.
/Users/antares/Development/RabbitMQ/umbrella.git/deps/rabbitmq_dotnet_client/projects/client/Apigen/Apigen.csproj : warning NU1701: Package 'System.Xml.XPath.XmlDocument 4.0.0' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETCoreApp,Version=v2.0'. This package may not be fully compatible with your project.
/Users/antares/Development/RabbitMQ/umbrella.git/deps/rabbitmq_dotnet_client/projects/client/Apigen/Apigen.csproj : warning NU1701: Package 'System.Xml.XPath.XmlDocument 4.0.0' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETCoreApp,Version=v2.0'. This package may not be fully compatible with your project.
/Users/antares/Development/RabbitMQ/umbrella.git/deps/rabbitmq_dotnet_client/projects/client/RabbitMQ.Client/src/client/api/ShutdownEventArgs.cs(113,1): error CS1022: Type or namespace definition, or end-of-file expected [/Users/antares/Development/RabbitMQ/umbrella.git/deps/rabbitmq_dotnet_client/projects/client/ApigenBootstrap/ApigenBootstrap.csproj]
```

**Comment by michaelklishin** [comment]
My branch does include 9cc1cba9726508b7197b034e900b2462c29b5b13.

**Comment by paulomorgado** [comment]
I have only changed existing .cs files. I have no clue why it doesn't compile.

**Comment by michaelklishin** [comment]
@paulomorgado please take a look at the error. `ShutdownEventArgs.cs` is one of the files changed in this PR, including line 113. Another data point: things compile just fine in master.

**Comment by michaelklishin** [comment]
OK, there was an extra closing `}` at the end of that file. Now I'm getting a different compilation failure:

```
(CoreCompile target) ->
  src/client/impl/UnknownClassOrMethodException.cs(65,26): error CS0103: The name 'Constants' does not exist in the current context [/Users/antares/Development/RabbitMQ/umbrella.git/deps/rabbitmq_dotnet_client/projects/client/RabbitMQ.Client/RabbitMQ.Client.csproj]
  src/client/impl/Frame.cs(147,32): error CS0103: The name 'Constants' does not exist in the current context [/Users/antares/Development/RabbitMQ/umbrella.git/deps/rabbitmq_dotnet_client/projects/client/RabbitMQ.Client/RabbitMQ.Client.csproj]
  src/client/impl/Frame.cs(239,35): error CS0103: The name 'Constants' does not exist in the current context [/Users/antares/Development/RabbitMQ/umbrella.git/deps/rabbitmq_dotnet_client/projects/client/RabbitMQ.Client/RabbitMQ.Client.csproj]
```

another file modified in this PR which deletes two `using` statements (which has nothing to do with the goal of this PR).

**Comment by michaelklishin** [comment]
And then `UnknownClassOrMethodException.cs`. I'm sorry but this PR changes more than it advertises, does not compile and "I have no idea why it doesn't compile" is not an argument that our team of maintainers can accept.

Not going forward with this one.

**Comment by paulomorgado** [comment]
I've fixed the issues and am now able to build.

**Pull request closed without merging**
