### PR TITLE
Remove use of Moq

### LINKED ISSUE #1369: Remove the use of Moq
### Is your feature request related to a problem? Please describe.

Moq 4.20 and later collects telemetry data that we do not wish to participate in:

https://www.bleepingcomputer.com/news/security/popular-open-source-project-moq-criticized-for-quietly-collecting-data/

https://yro.slashdot.org/story/23/08/09/2058205/popular-open-source-project-moq-criticized-for-quietly-collecting-data

https://github.com/moq/moq/commit/6057dd207f597db2b8f9acc74f1fec9c8c0a2655

### Describe the solution you'd like

Remove `Moq`

### PR DESCRIPTION
**Pull request by lukebakken**
Fixes #1369

### CODE REVIEW

**Review by MarcialRosales — COMMENTED** [review]
Hi @lukebakken , rather than implementing ourselves the mocking mechanism, would it make sense to use other library instead of Moq?

**Comment by michaelklishin** [comment]
@MarcialRosales if you have a good alternative to suggest that does not collect telemetry data, sure.

**Comment by lukebakken** [comment]
> Hi @lukebakken , rather than implementing ourselves the mocking mechanism, would it make sense to use other library instead of Moq?

We can do that if the future need arises. For now, the amount of code that needs to be hand-written is small.

**Comment by MarcialRosales** [comment]
@michaelklishin , I will look into that .  For now, https://www.libhunt.com/r/NSubstitute, looks like the best alternative. 
@lukebakken , for the time being, we can live with a handcrafted mock.

**Pull request merged**
