### PR TITLE
Removing the ApiGen project.

### LINKED ISSUE #742: Re-consider per-build AMQP API generation
See [this comment](https://github.com/rabbitmq/rabbitmq-dotnet-client/issues/741#issuecomment-593123031) in #741

### PR DESCRIPTION
**Pull request by stebet**
# Proposed Changes
Removes the ApiGen project and brings code into separate files (resolves #742)
Style cleanups to make code more uniform.
Simplified AMQP Class-Method parsing and handling.

## Types of Changes

- [X] Bug fix (non-breaking change which fixes issue #742)
- [ ] New feature (non-breaking change which adds functionality)
- [X] Breaking change (fix or feature that would cause an observable behavior change in existing systems)
- [ ] Documentation improvements (corrections, new content, etc)
- [X] Cosmetic change (whitespace, formatting, etc)

## Checklist

- [X] I have read the `CONTRIBUTING.md` document
- [X] I have signed the CA (see https://cla.pivotal.io/sign/rabbitmq)
- [X] All tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in related repositories

### CODE REVIEW

**Comment by michaelklishin** [comment]
@stebet thank you for your ongoing contributions. FYI we may or may not have a chance to get to this till mid-next week.

**Comment by michaelklishin** [comment]
@stebet can you please rebase this on top of `master`?

**Comment by bollhals** [comment]
Is this something that we consider doing? I might be able to take a look on that if you want.

**Comment by michaelklishin** [comment]
@bollhals yes, we have agreed that the generation part arguably takes more time to maintain than it saves. The protocol doesn't change very often.

**Comment by stebet** [comment]
Currently working on a rebase of the full-async branch. It's a bit time consuming but I should get it done in the next days. Ramping productivity back up after summer vacations ;)

**Comment by michaelklishin** [comment]
I assume #924 supersedes this.

**Pull request closed without merging**
