### PR TITLE
Removed allot of casting from the code.

### PR DESCRIPTION
**Pull request by YulerB**
## Proposed Changes

Removing casting using generics, and correct typing.

## Types of Changes

- [ ] Bugfix (non-breaking change which fixes issue #NNNN)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation (correction or otherwise)
- [] Cosmetics (white space, appearance)

## Checklist

- [x] I have read the `CONTRIBUTING.md` document
- [x] I have signed the CA (see https://cla.pivotal.io/sign/rabbitmq)
- [x] All tests pass locally with my changes
- [x] I have added tests that prove my fix is effective or that my feature works
- [] I have added necessary documentation (if appropriate)
- [] Any dependent changes have been merged and published in related repositories

### CODE REVIEW

**Comment by paulomorgado** [comment]
`ushort` is not [CLS compliant](https://docs.microsoft.com/en-us/dotnet/standard/language-independence-and-language-independent-components#Types). The code should move away from `ushort`  and not towards it.

**Comment by bording** [comment]
> ushort is not CLS compliant. The code should move away from ushort and not towards it.

@paulomorgado Given that the underlying AMQP protocol relies on unsigned values, I don't think it's possible or desirable to do that.

**Comment by paulomorgado** [comment]
@bording, like many Windows APIs. And, yet, you won't find a .NET public API that is not CLS compliant.

**Comment by kjnilsson** [comment]
I merged this with some changes. I don't have a problem with using the most appropriate type of the fields in question. We can have a separate discussion as to what it is we want to achieve or not with CLS compliancy.

**Pull request merged**
