### PR TITLE
use cached empty BasicProperties when null

### PR DESCRIPTION
**Pull request by bollhals**
## Proposed Changes

Instead of creating a new BasicProperties when the passed one is null, a cached empty one is used. This avoids creating a new instance every time.

## Types of Changes

- [ ] Bug fix (non-breaking change which fixes issue #NNNN)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause an observable behavior change in existing systems)
- [ ] Documentation improvements (corrections, new content, etc)
- [ ] Cosmetic change (whitespace, formatting, etc)

## Checklist

- [x] I have read the `CONTRIBUTING.md` document
- [x] I have signed the CA (see https://cla.pivotal.io/sign/rabbitmq)
- [ ] All tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in related repositories

## Further Comments

edited as I accidentally posted it too early

### CODE REVIEW

**Comment by michaelklishin** [comment]
Makes perfect sense to me. Thank you!

**Comment by michaelklishin** [comment]
Backported to `6.x`.

**Comment by AStove** [comment]
Just because `internal readonly IBasicProperties _emptyBasicProperties;` is "readonly" doesn't mean you can't change the properties of the object that referenced by `_emptyBasicProperties`. It just means you can't assign a new object to it outside of the constructor.

I think it's fine now but it could introduce some bugs later if the objects decide to make modifications to the properties they receive and thus your `_emptyBasicProperties` gets changed aswell. Solution would be to clone the object on passing but then what have we achieved with caching it.

https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/readonly
> Because reference types contain a reference to their data, a field that is a readonly reference type must always refer to the same object. That object isn't immutable. The readonly modifier prevents the field from being replaced by a different instance of the reference type. However, the modifier doesn't prevent the instance data of the field from being modified through the read-only field.

**Comment by stebet** [comment]
The cached object is only used when sending data and no properties have been set, so it should never be able to be modified, except through reflection.

**Pull request merged**
