### PR TITLE
Run "dotnet format"

### LINKED ISSUE #1192: Automatic code formatting
In https://github.com/rabbitmq/rabbitmq-dotnet-client/pull/692, @stebet contributed an `.editorconfig` file that is based on this - https://github.com/dotnet/runtime/blob/main/.editorconfig

In this PR (https://github.com/rabbitmq/rabbitmq-stream-dotnet-client/pull/78) I added the `.editorconfig` from this project - https://github.com/dotnet/format/blob/main/.editorconfig

We should review the settings in these files and, perhaps, take some other configs into account (https://github.com/dotnet/roslyn/blob/main/.editorconfig)

...then format all the code and add code to the GH actions to verify formatting.

@stebet let me know if you'd like me to wait for #949 updates before running `dotnet format` on this project.

### PR DESCRIPTION
**Pull request by lukebakken**
Fixes #1192

Also adds a format check to CI

### CODE REVIEW

**Comment by ArminShoeibi** [comment]
Hi there @lukebakken, May I create a PR for changing whole codebase namespaces to file scoped mode?

**Comment by lukebakken** [comment]
@ArminShoeibi that would be appreciated.

**Comment by ArminShoeibi** [comment]
> @ArminShoeibi that would be appreciated.

Thank you, I'm on it.

**Comment by ArminShoeibi** [comment]
> @ArminShoeibi that would be appreciated.

Hello there Luke @lukebakken
Thank you in advance.
https://github.com/rabbitmq/rabbitmq-dotnet-client/pull/1202

**Pull request merged**
