### PR TITLE
incorrect retrieval of milliseconds for timeout

### LINKED ISSUE #385: Incorrect read timeout during start and tune
https://github.com/rabbitmq/rabbitmq-dotnet-client/blob/c698ba41d859bca3e3bb91e7d5075ec85f1f9136/projects/client/RabbitMQ.Client/src/client/impl/Connection.cs#L1284

Should probably have been `TotalMilliseconds `instead of `Milliseconds`. Default is 10 seconds which will translate into 0 milliseconds in the current implementation which will set the socket to have an infinite receive timeout.

### PR DESCRIPTION
**Pull request by Fresa**
## Proposed Changes

Fixes #385.

## Types of Changes

- [X] Bugfix (non-breaking change which fixes issue #385)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation (correction or otherwise)
- [ ] Cosmetics (whitespace, appearance)

## Checklist

- [X] I have read the `CONTRIBUTING.md` document
- [x] I have signed the CA (see https://cla.pivotal.io/sign/rabbitmq)
- [X] All tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in related repositories

## Further Comments

N/A

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@Fresa Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/rabbitmq?repositoryId=rabbitmq/rabbitmq-dotnet-client&pullRequestId=386)!

[Click here](https://cla.pivotal.io/sync/rabbitmq?repositoryId=rabbitmq/rabbitmq-dotnet-client&pullRequestId=386) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@Fresa Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/rabbitmq?repositoryId=rabbitmq/rabbitmq-dotnet-client&pullRequestId=386)!

**Comment by lukebakken** [comment]
Thank you!

**Comment by michaelklishin** [comment]
Backported to `4.x` in 06f649eb3b142007ba0ff4d0c15dbba5cc371a63. @kjnilsson I think it's a good enough of a reason to do a new 4.x release.

**Pull request merged**
