### PR TITLE
simplify CloseReason handling & improve AutorecoveringConnection eventing

### PR DESCRIPTION
**Pull request by bollhals**
## Proposed Changes

- Simplifies the handling of the close reason (no locking required)
- improves how the event recovering is done for AutoRecoveringConnection

## Types of Changes

- [ ] Bug fix (non-breaking change which fixes issue #NNNN)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause an observable behavior change in existing systems)
- [ ] Documentation improvements (corrections, new content, etc)
- [ ] Cosmetic change (whitespace, formatting, etc)

## Checklist

- [x] I have read the `CONTRIBUTING.md` document
- [x] I have signed the CA (see https://cla.pivotal.io/sign/rabbitmq)
- [x] All tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in related repositories

### CODE REVIEW

**Comment by michaelklishin** [comment]
I get test failures in

``` shell
RABBITMQ_RABBITMQCTL_PATH=rabbitmqctl dotnet test projects/Unit --filter "FullyQualifiedName~RabbitMQ.Client.Unit.TestConnectionRecovery"
```

on this branch but not `master`.

**Comment by michaelklishin** [comment]
One example failure:

```
  X TestBasicAckEventHandlerRecovery [14s 428ms]
  Error Message:
     waiting on a latch timed out
  Expected: True
  But was:  False

  Stack Trace:
     at RabbitMQ.Client.Unit.IntegrationFixture.Wait(ManualResetEventSlim latch) in rabbitmq_dotnet_client.git/projects/Unit/Fixtures.cs:line 474
   at RabbitMQ.Client.Unit.TestConnectionRecovery.CloseAndWaitForRecovery(AutorecoveringConnection conn) in rabbitmq_dotnet_client.git/projects/Unit/TestConnectionRecovery.cs:line 953
   at RabbitMQ.Client.Unit.TestConnectionRecovery.CloseAndWaitForRecovery() in rabbitmq_dotnet_client.git/projects/Unit/TestConnectionRecovery.cs:line 944
   at RabbitMQ.Client.Unit.TestConnectionRecovery.TestBasicAckEventHandlerRecovery() in rabbitmq_dotnet_client.git/projects/Unit/TestConnectionRecovery.cs:line 114
```

**Comment by bollhals** [comment]
I had the same locally, but I fixed it. The I was able to run these tests 30x without issues.
Not sure though wether the fix made it into the PR. 🤔 Let me have another look

**Comment by bollhals** [comment]
> I had the same locally, but I fixed it. The I was able to run these tests 30x without issues.
> Not sure though wether the fix made it into the PR. 🤔 Let me have another look

yes, was still in the stash, sorry for that.

**Review by michaelklishin — APPROVED** [review]

**Comment by michaelklishin** [comment]
Thank you!

**Pull request merged**
