### PR TITLE
Deletion of unused UseBackgroundThreadsForIO

### PR DESCRIPTION
**Pull request by Pliner**
## Proposed Changes

Delettion of unused property `UseBackgroundThreadsForIO`.

## Types of Changes

- [ ] Bug fix (non-breaking change which fixes issue #NNNN)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause an observable behavior change in existing systems)
- [ ] Documentation improvements (corrections, new content, etc)
- [ ] Cosmetic change (whitespace, formatting, etc)

## Checklist

- [x] I have read the `CONTRIBUTING.md` document
- [x] I have signed the CA (see https://cla.pivotal.io/sign/rabbitmq)
- [ ] All tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in related repositories

### CODE REVIEW

**Comment by michaelklishin** [comment]
@bording @lukebakken @stebet just to be sure: if we include this into `6.1.0`, does this count as a "minor breaking API change"?

**Comment by michaelklishin** [comment]
@Pliner good catch, thanks.

**Comment by michaelklishin** [comment]
Backported to `6.x`. Thank you!

**Comment by bording** [comment]
> @bording @lukebakken @stebet just to be sure: if we include this into `6.1.0`, does this count as a "minor breaking API change"?

Yes, this is a breaking change. It should not be backported to 6.x

**Comment by stebet** [comment]
It's a no-op but yes, breaking as removing it'll trigger a compilation error. I'd say for 6.x mark is with a [Deprecated] attribute.

**Comment by michaelklishin** [comment]
Actually this was not backported to `6.x`, #847 was, but I've mixed up a tab and left a comment here.

**Pull request merged**
