### PR TITLE
make implementations internal and sealed

### LINKED ISSUE #466: Make implementation internal
As an exercise, I made almost every implementation detail internal: https://github.com/paulomorgado/rabbitmq-dotnet-client/tree/internal

There's surely room for improvement. But I think it's a good start.

### PR DESCRIPTION
**Pull request by paulomorgado**
## Proposed Changes

The code base is filled with unnecessary public types or members and unnecessary virtual members.

This PR locks down everything possible to lock down.

Fixes #466 

## Types of Changes

- [ ] Bugfix (non-breaking change which fixes issue #NNNN)
- [ ] New feature (non-breaking change which adds functionality)
- [X] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation (correction or otherwise)
- [ ] Cosmetics (whitespace, appearance)

## Checklist

- [X] I have read the `CONTRIBUTING.md` document
- [X] I have signed the CA (see https://cla.pivotal.io/sign/rabbitmq)
- [ ] All tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in related repositories

### CODE REVIEW

**Comment by paulomorgado** [comment]
I think I got it solved.

I'm still having some trouble setting up a test environment. I'm running the server from a container but the tests are missing some rabbitmqctl.bat file. Is there a way to get it without having to install a server locally.

**Comment by michaelklishin** [comment]
@paulomorgado RabbitMQ CLI tools ship with the broker.

**Comment by paulomorgado** [comment]
@michaelklishin, can you tell me why the tests are failing now?

**Comment by michaelklishin** [comment]
The only error I could spot was

```
CSC : error CS1617: Invalid option '7.3' for /langversion. Use '/langversion:?' to list supported values. [/tmp/build/b95f7b06/rabbitmq_dotnet_client/projects/client/Unit/Unit.csproj]
    0 Warning(s)rifying Checksum
    1 Error(s)Download complete
```

**Comment by paulomorgado** [comment]
You need to upgrade the build tools on that build server.

**Comment by michaelklishin** [comment]
We will. Note that we are happy to merge your contributions if they pass on our developer machines and update Concourse environment(s) later.

**Comment by bording** [comment]
@kjnilsson If you're actually running against the latest .NET Core SDK, then I would expect it to understand the 7.3 langversion. It seems like you've got something wrong in your CI still.

**Comment by kjnilsson** [comment]
```root@29fc37abe41d:/# dotnet --version
2.1.4```

**Comment by kjnilsson** [comment]
It builds ok if we remove LangVersion - please update the PR without a specific lang version (Why only add it for Unit anyway?). Cheers.

**Comment by bording** [comment]
> It doesn't build ok at all with no langversion but 7.2 seems ok

If you don't specify a language version, it defaults to the latest major version of the C# language, which right now means 7.0. So if you're using any language features introduced in 7.1, 7.2, or 7.3, you'll get errors.

BTW, the `LangVersion` property also accepts "latest" as a value, which would let the project pick up the newest language features without needing to update the project value.

**Comment by paulomorgado** [comment]
@bording, `latest` in my machine is `7.3`. That's why it's a good practice to make the version explicit.

Meanwhile, I was able to make it work with `7.0` (`default`).

**Pull request merged**
