### PR TITLE
Initial implementation of full-async.

### PR DESCRIPTION
**Pull request by stebet**
## Proposed Changes

First PR for the full-async version of the client. The aim here has been minimal API changes (except for Task based methods of course), performance improvements, allocation reductions and code cleanups. This now targets .NET Standard 2.0 exclusively and takes advantage of `System.IO.Pipelines` as well as `Pipelines.Sockets.Unofficial`.

This is by no means a completed PR, but is added to this separate branch for a clearer separation.

There is a big to-do list that is still left to work on.

- [ ] Decide whether to stop using ApiGen and move generated code into concrete classes (assumes that protocol won't change and new server features are rare for 0.9.1)
- [ ] Clean up code layout to reduce duplicate class names and possible confusion
- [ ] Code cleanups
- [ ] API simplification (Converge ISession and SocketFrameHandler into Connection?, remove unnecessary interfaces, move internal classes to structs where possible, etc.)
- [ ] Add even more tests
- [ ] Decide if methods should always return ValueTask or use a Task when they are guaranteed to always run asynchronously.
- [ ] Should we get rid of WaitForConfirms and rather have the BasicPublish not return until a message has been 'ack'ed if SelectConfirm has been turned on?

## Types of Changes

- [ ] Bug fix (non-breaking change which fixes issue #NNNN)
- [X] New feature (non-breaking change which adds functionality)
- [X] Breaking change (fix or feature that would cause an observable behavior change in existing systems)
- [ ] Documentation improvements (corrections, new content, etc)
- [ ] Cosmetic change (whitespace, formatting, etc)

## Checklist

- [X] I have read the `CONTRIBUTING.md` document
- [X] I have signed the CA (see https://cla.pivotal.io/sign/rabbitmq)
- [ ] All tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in related repositories

## Further Comments

This is a pretty big breaking change, but I've tried to keep API changes to a minimum, however I've also spotted several places where code can be simplified.

### CODE REVIEW

**Comment by stebet** [comment]
Adding @danielmarbach as well for visibility.

**Comment by lukebakken** [comment]
> Decide whether to stop using ApiGen and move generated code into concrete classes (assumes that protocol won't change and new server features are rare for 0.9.1)

Yes, we should do this (#742). If possible as a separate PR because the amount of change here is already pretty overwhelming :flushed:

**Comment by stebet** [comment]
I'm going to accept this PR as a starting point for refinements such as #742 so we can start pushing experimental PRs into it. Do you have a workflow for experimental work like this? At what point would you want to make a go/no-go on this direction and when should this be either abandoned or green-lit to move from experiment to active development?

I think it'd make sense to create issues and tag them appropriately at least so they aren't confused with issues relating to versions that have already been released.

**Comment by lukebakken** [comment]
@stebet ideally the changes in this PR would be approved ASAP to prevent "long running branch" syndrome. If @bording or @danielmarbach could take a look here that would be very much appreciated.

**Comment by stebet** [comment]
Yeah, thing is with a change like this, it's hard to do anything gradually. That's why I suggested a different branch. I can work on keeping it up to date with the applicable master changes as well, but a good review would go far, but I realize with the amount and nature of the changes, they can look daunting.

Don't hesitate to comment on any changes you feel need an explanation or a closer look and I'll do my best to respond quickly.

**Comment by danielmarbach** [comment]
@lukebakken 

Wouldn't it make more sense from a high level perspective to first align on the following corner stones:

- Target framework
- Async only? Sync over async with all the dangers or go down the extra effort of providing a redundant sync path with the async
- Value Task vs Task
- Other topics?

From a long term perspective it might also be interesting to hear your plans on whether the broker will standardize on AMQP 1.0 for the client communication. If it would we might need to address async in different ways like for example switching the guts of it to a proper AMQP lib. 

But that is more a side point to indicate that I feel a well communicated plan that we hash out and potentially gets announced over your blogs might make sense

**Comment by stebet** [comment]
> @lukebakken
> 
> Wouldn't it make more sense from a high level perspective to first align on the following corner stones:
> 
> * Target framework
> * Async only? Sync over async with all the dangers or go down the extra effort of providing a redundant sync path with the async
> * Value Task vs Task
> * Other topics?
> 
> From a long term perspective it might also be interesting to hear your plans on whether the broker will standardize on AMQP 1.0 for the client communication. If it would we might need to address async in different ways like for example switching the guts of it to a proper AMQP lib.
> 
> But that is more a side point to indicate that I feel a well communicated plan that we hash out and potentially gets announced over your blogs might make sense

I totally agree with this. There are a lot of things to consider here. Personally, I'm of the opinion that if a big breaking API change is going to be made, you might as well take it as far as possible without completely turning everything on it's head, which I feel this change does by mostly being a transition of Sync->Async, keeping the other implementation details, but of course I'm a bit biased being the one who created it.

Would this be a good place to have those discussions or is there a better venue?

**Comment by danielmarbach** [comment]
I'm happy to be part of a call and then together summarize the thoughts on an issue.

**Comment by stebet** [comment]
> I'm happy to be part of a call and then together summarize the thoughts on an issue.

Me too. @lukebakken and @michaelklishin would you like to organize a call? I think having @bording as well would be great if we can find a time that suits everyone.

**Comment by danielmarbach** [comment]
I'm CEST, if I'm not mistaken @bording is in EDT.

**Comment by stebet** [comment]
I'm on UTC time :)

**Comment by lukebakken** [comment]
> From a long term perspective it might also be interesting to hear your plans on whether the broker will standardize on AMQP 1.0 for the client communication

There are no plans to do this that I know of. AMQP 1.0 bears no relation to 0.9.1 and can't even be called a "successor" ... it's just different.

I'm glad @danielmarbach, @stebet and @bording have the opinions and expertise to take the lead on this. I haven't worked day-to-day with .NET since 2013 which is probably evident in my comments here. I'll come up with a way to coordinate a call. If you'd like to email me your contact information, my email is available on my public GitHub profile. Thanks.

**Comment by bording** [comment]
> I'm CEST, if I'm not mistaken @bording is in EDT.

Yes, that is correct!

**Pull request merged**
