### PR TITLE
Event args cancellation

### PR DESCRIPTION
**Pull request by danielmarbach**
## Proposed Changes

This introduces the possibility to allow the cancellation to flow into the async event handlers

## Types of Changes

What types of changes does your code introduce to this project?
_Put an `x` in the boxes that apply_

- [ ] Bug fix (non-breaking change which fixes issue #NNNN)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause an observable behavior change in existing systems)
- [ ] Documentation improvements (corrections, new content, etc)
- [ ] Cosmetic change (whitespace, formatting, etc)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating
the PR. If you're unsure about any of them, don't hesitate to ask on the
mailing list. We're here to help! This is simply a reminder of what we are
going to look for before merging your code._

- [x] I have read the `CONTRIBUTING.md` document
- [x] I have signed the CA (see https://cla.pivotal.io/sign/rabbitmq)
- [ ] All tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in related repositories

## Further Comments

If this is a relatively large or complex change, kick off the discussion by
explaining why you chose the solution you did and what alternatives you
considered, etc.

### CODE REVIEW

**Comment by danielmarbach** [comment]
@lukebakken I started implementing the cancellation support into the event handler wrapper. This is far from done but here is a headsup

**Comment by danielmarbach** [comment]
FYI I did not setup the commit signing on my temporary device while my main macbook is on repair. That is why some commits are not signed

**Comment by danielmarbach** [comment]
I will double-check things once more, but I guess it doesn't hurt start reviewing it

**Comment by danielmarbach** [comment]
@lukebakken do you know why `AsyncEventingWrapper` is a struct? Seems unnecessary because we use them as fields on objects that don't get allocated a ton.

**Comment by lukebakken** [comment]
I can look in the commit history. The choice of `struct` for the event wrappers came from a community-contributed PR, most likely from @bollhals or @stebet 

I'm perfectly happy changing them to `class` for the reasons you stated.

**Comment by danielmarbach** [comment]
Those are two pretty smart blokes. I don't want to jump the gun ;)

**Comment by lukebakken** [comment]
FYI, I'm addressing the `TODO` you added around `ShutdownEventArgs` in a branch that depends on this one. I'm also finally fixing the directory structure so that it matches the namespaces, because that has driven me nuts for years.

**Review by lukebakken — APPROVED** [review]
Thank you yet again @danielmarbach

**Pull request merged**
