### PR TITLE
:mag_right: Sourcelink added!

### LINKED ISSUE #697: Support source linking
Supercedes #484 

https://docs.microsoft.com/en-us/dotnet/standard/library-guidance/sourcelink

### PR DESCRIPTION
**Pull request by PureKrome**
## Proposed Changes
Adding source link to the main client-package.

Fixes #697 

## Types of Changes

- [ ] Bug fix (non-breaking change which fixes issue #NNNN)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause an observable behavior change in existing systems)
- [ ] Documentation improvements (corrections, new content, etc)
- [ ] Cosmetic change (whitespace, formatting, etc)

## Checklist

- [X] I have read the `CONTRIBUTING.md` document
- [X] I have signed the CA (see https://cla.pivotal.io/sign/rabbitmq)
- [X] All tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in related repositories

## Further Comments

This is one of 2x files that need to be modified. 
The second file is the shell script which you run on Debian.

```
# pack without re-building to ensure we include the strongnamed dlls
# NOTE: this should create a .nupkg and a .snupkg file.
dotnet pack ./projects/client/RabbitMQ.Client --no-build --configuration SignedRelease

# push the packages
dotnet nuget push -k "$NUGET_API_KEY" -s https://www.nuget.org/api/v2/package \
    ./projects/client/RabbitMQ.Client/bin/SignedRelease/RabbitMQ.Client.*.nupkg
dotnet nuget push -k "$NUGET_API_KEY" -s https://www.nuget.org/api/v2/package \
    ./projects/client/RabbitMQ.Client/bin/SignedRelease/RabbitMQ.Client.*.snupkg
```

This code was referenced off [another GH repo](https://github.com/PureKrome/HttpClient.Helpers) where I was doing this type of stuff (with a different CI build system, but still a reference point).

The `dotnet pack` command should create both a `.nupkg` and a `.snupkg` file, now that the new info is added to the `.csproj` file for that project. Then we just push both up to nuget.

It looks like this (in nuget.org):

image

### CODE REVIEW

**Comment by bording** [comment]
@michaelklishin While Microsoft might be pushing for these extra symbol packages, I've never found the reasoning for using them convincing. The primary argument is that symbol files increase the size of the NuGet package, so you shouldn't include them. However, especially since the creation portable PDB format, they are rather small files. I tend to think their argument only really makes sense for the things they ship, the actual framework symbols.

To save that file size, you now have to deal with multiple packages, and have your debugger know how to find and download the extra packages when it needs them. I know Visual Studio can do this, but I'm not sure if other tools can or not.

On the other hand, you could just bundle the PDB directly in the main NuGet package, and then it's right there all the time, ready to go. It also means that if you want to deploy the PDB as a production artifact to get line numbers in exception stack traces, they are already right there available for you.

There is a [bug](https://github.com/dotnet/sdk/issues/1458) that can impact the "just bundle the PDF in the main package approach" that hasn't been fixed yet, so that does currently prevent Source Link from working when you hit that bug.

At this point, I think what I'd recommend here is to do both. Go ahead and create and upload the extra symbol package, but also include the PDB in the main package. That could be accomplished by adding the following line to this PR:
```
<AllowedOutputExtensionsInPackageBuildOutputFolder>$(AllowedOutputExtensionsInPackageBuildOutputFolder);.pdb</AllowedOutputExtensionsInPackageBuildOutputFolder>
```

**Comment by lukebakken** [comment]
Running into this issue in our CI environment, even though this branch builds fine on Windows 10 and my local Debian 10 VM (which should be identical). Investigating it -

```
+ cd /tmp/build/b95f7b06/rabbitmq_dotnet_client
+ ./build.sh
  Restore completed in 1.49 sec for /tmp/build/b95f7b06/rabbitmq_dotnet_client/projects/client/Apigen/Apigen.csproj.
  Restore completed in 1.86 sec for /tmp/build/b95f7b06/rabbitmq_dotnet_client/projects/client/RabbitMQ.Client/RabbitMQ.Client.csproj.
  Restore completed in 11.26 sec for /tmp/build/b95f7b06/rabbitmq_dotnet_client/projects/client/Unit/Unit.csproj.
* Loading spec from '/tmp/build/b95f7b06/rabbitmq_dotnet_client/docs/specs/amqp0-9-1.stripped.xml'
* Parsing spec for version 0.9.1
* Generating code into '/tmp/build/b95f7b06/rabbitmq_dotnet_client/gensrc/autogenerated-api-0-9-1.cs'
Microsoft (R) Build Engine version 16.4.0+e901037fe for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  Restore completed in 55.73 ms for /tmp/build/b95f7b06/rabbitmq_dotnet_client/projects/client/Unit/Unit.csproj.
  Restore completed in 54.27 ms for /tmp/build/b95f7b06/rabbitmq_dotnet_client/projects/client/RabbitMQ.Client/RabbitMQ.Client.csproj.
  Restore completed in 54.27 ms for /tmp/build/b95f7b06/rabbitmq_dotnet_client/projects/client/Apigen/Apigen.csproj.
  Apigen -> /tmp/build/b95f7b06/rabbitmq_dotnet_client/projects/client/Apigen/bin/Debug/netcoreapp2.1/Apigen.dll
/root/.nuget/packages/microsoft.build.tasks.git/1.0.0/build/Microsoft.Build.Tasks.Git.targets(24,5): error : Error reading git repository information: Found invalid data while decoding. [/tmp/build/b95f7b06/rabbitmq_dotnet_client/projects/client/RabbitMQ.Client/RabbitMQ.Client.csproj]
/root/.nuget/packages/microsoft.build.tasks.git/1.0.0/build/Microsoft.Build.Tasks.Git.targets(24,5): warning : Unable to locate repository with working directory that contains directory '/tmp/build/b95f7b06/rabbitmq_dotnet_client/projects/client/RabbitMQ.Client'. [/tmp/build/b95f7b06/rabbitmq_dotnet_client/projects/client/RabbitMQ.Client/RabbitMQ.Client.csproj]
/root/.nuget/packages/microsoft.build.tasks.git/1.0.0/build/Microsoft.Build.Tasks.Git.targets(24,5): error : Error reading git repository information: Found invalid data while decoding. [/tmp/build/b95f7b06/rabbitmq_dotnet_client/projects/client/RabbitMQ.Client/RabbitMQ.Client.csproj]
/root/.nuget/packages/microsoft.build.tasks.git/1.0.0/build/Microsoft.Build.Tasks.Git.targets(24,5): warning : Unable to locate repository with working directory that contains directory '/tmp/build/b95f7b06/rabbitmq_dotnet_client/projects/client/RabbitMQ.Client'. [/tmp/build/b95f7b06/rabbitmq_dotnet_client/projects/client/RabbitMQ.Client/RabbitMQ.Client.csproj]

Build FAILED.

/root/.nuget/packages/microsoft.build.tasks.git/1.0.0/build/Microsoft.Build.Tasks.Git.targets(24,5): warning : Unable to locate repository with working directory that contains directory '/tmp/build/b95f7b06/rabbitmq_dotnet_client/projects/client/RabbitMQ.Client'. [/tmp/build/b95f7b06/rabbitmq_dotnet_client/projects/client/RabbitMQ.Client/RabbitMQ.Client.csproj]
/root/.nuget/packages/microsoft.build.tasks.git/1.0.0/build/Microsoft.Build.Tasks.Git.targets(24,5): warning : Unable to locate repository with working directory that contains directory '/tmp/build/b95f7b06/rabbitmq_dotnet_client/projects/client/RabbitMQ.Client'. [/tmp/build/b95f7b06/rabbitmq_dotnet_client/projects/client/RabbitMQ.Client/RabbitMQ.Client.csproj]
/root/.nuget/packages/microsoft.build.tasks.git/1.0.0/build/Microsoft.Build.Tasks.Git.targets(24,5): error : Error reading git repository information: Found invalid data while decoding. [/tmp/build/b95f7b06/rabbitmq_dotnet_client/projects/client/RabbitMQ.Client/RabbitMQ.Client.csproj]
/root/.nuget/packages/microsoft.build.tasks.git/1.0.0/build/Microsoft.Build.Tasks.Git.targets(24,5): error : Error reading git repository information: Found invalid data while decoding. [/tmp/build/b95f7b06/rabbitmq_dotnet_client/projects/client/RabbitMQ.Client/RabbitMQ.Client.csproj]
    2 Warning(s)
    2 Error(s)
```

**Comment by lukebakken** [comment]
I added the following `git` commands to see if they show anything useful -

```
export GIT_PAGER='cat'
git config --global --list
git config --local --list
git branch
git remote -v
git submodule update --init
```

Here is the output which doesn't seem to show anything is off: 
[ci-build-output-git-commands.txt](https://github.com/rabbitmq/rabbitmq-dotnet-client/files/4142831/ci-build-output-git-commands.txt)

Also see https://github.com/dotnet/sourcelink/issues/347

At the moment I don't see any obvious reason for these build errors.

**Comment by PureKrome** [comment]
> @ the errors:

er... i've not stumbled across that before :( I've done this on windows and ubuntu machines. So .. maybe this might be above my paygrade?

> @ including PDB.

My vote is to *not* include that. MS frameworks or not, I just don't want extra stuff for the 99% of the time I don't need it. If it's that 1% of the time I do need it, then let me grab it. Keep it simple. Keep it lean.

**Comment by lukebakken** [comment]
I'm debugging this issue on our CI infrastructure.

**Comment by PureKrome** [comment]
I can't access the CI build report, to help debug / review the detailed build output.  soz :/

**Comment by lukebakken** [comment]
It's not public. I have determined that the issue is in how [this Concourse resource](https://github.com/jtarchie/github-pullrequest-resource) clones the pull request. If I clone your fork and switch to this PR's branch, the build is fine.

@gerhard the next thing I would like to try is switching to [this resource](https://github.com/telia-oss/github-pr-resource) for PR builds for this client. If it fixes this issue, we may want to use it for all PR builds.

**Comment by gerhard** [comment]
@lukebakken go for it!

**Comment by PureKrome** [comment]
/me feels bad because my PR has caused more work than intended 😢

**Comment by lukebakken** [comment]
Using the new PR image for concourse the build still fails, but it's a different reason now: 
[ci-build-output-2020-02-04.txt](https://github.com/rabbitmq/rabbitmq-dotnet-client/files/4156534/ci-build-output-2020-02-04.txt)

**Comment by lukebakken** [comment]
Commit 5ec3241e9213296126bbe40231c9ba29fc19cd0e fixes the issue, however I'm not thrilled about doing `git` manipulation from this project's build scripts. I'm going to add that to our CI scripts instead. If someone clones this repo and screws up their remotes then hopefully they can find their way to this issue to figure it out 😸

**Comment by lukebakken** [comment]
@PureKrome @bording if you have a moment to test this build for correct sourcelink and pdb behavior, I would appreciate it:

https://www.myget.org/feed/rabbitmq/package/nuget/RabbitMQ.Client/6.0.0-pr-1a7f4fb9

I'll do the same when I'm next using my Windows environment.

**Comment by PureKrome** [comment]
@lukebakken 

> to test this build for correct sourcelink and pdb behavior
> link: @ myget

I didn't think myget actually had a symbol server? I didn't think you could copy up the snupkg's? (and those symbols are needed I thought, if I wish to "step into" some method from the RabbitMQ.Client assembly.

**Comment by lukebakken** [comment]
@PureKrome the nupkg should be built with the pdb files embedded. Let me know if you find otherwise!

**Comment by bording** [comment]
@lukebakken I took at the package using the [Source Link testing tool](https://github.com/ctaggart/SourceLink#source-link-testing-tool) and everything mostly looks correct.

There is one file that should be embedded that isn't, so the testing tool reports a failure, but that is something I believe is related to a recent change to the C# compiler that had an unanticipated impact on source linking, and not something wrong with this PR.

I've noticed a similar problem in my projects, so it's something I'm going to be following up on to confirm it's a known issue.

**Comment by lukebakken** [comment]
Thanks a lot @bording - that's a handy tool to know about.

**Comment by lukebakken** [comment]
Thank you for your contribution @PureKrome

**Pull request merged**
