### PR TITLE
Update to PublicApiGenerator 10.0.2

### PR DESCRIPTION
**Pull request by lukebakken**
Remove copied-in code

Pinging @bording

### CODE REVIEW

**Comment by lukebakken** [comment]
Let's see if this survives a CI run...

**Comment by bording** [comment]
Looks like the changes to the approval file is all just some sorting differences, which is to be expected.

Looking at the size of the file, it would still be a really good idea to go through the types in the project and change the accessibility of most them to internal, which would make the file be a true representation of the public API surface.

**Comment by lukebakken** [comment]
> it would still be a really good idea to go through the types in the project and change the accessibility of most them to internal

That has been done in `master`. I'm probably not going to do that for `5.x` because I don't want to screw something up.

**Comment by bording** [comment]
> A lot of that has been done in master already, with more to be done post 6.0. I'm probably not going to do that for 5.x because I don't want to screw something up.

Sure, those kind of changes need to be done in a major. This PR is against `master` which is why I brought it up here.

**Comment by lukebakken** [comment]
@bording if you have time to "internalize" or "privatize" more parts of the public API prior to version 6.0, that would be great. I can't really get to that until I get `5.2.0` out the door.

**Comment by bording** [comment]
@lukebakken I'll see what I can do. I am going out of town this week, so I might not have time until next week.

**Pull request merged**
