### PR TITLE
remove task yield

### PR DESCRIPTION
**Pull request by bollhals**
## Proposed Changes

Removed the task.yield in the Work baseclass as well as the try catch, as there is already a try catch at the callee (Workpool of AsyncConsumerWorkService). This eliminates another chunk of allocations.

## Types of Changes

- [ ] Bug fix (non-breaking change which fixes issue #NNNN)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause an observable behavior change in existing systems)
- [ ] Documentation improvements (corrections, new content, etc)
- [ ] Cosmetic change (whitespace, formatting, etc)

## Checklist

- [x] I have read the `CONTRIBUTING.md` document
- [x] I have signed the CA (see https://cla.pivotal.io/sign/rabbitmq)
- [ ] All tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in related repositories

### CODE REVIEW

**Comment by bollhals** [comment]
I don't see a reason for the task.yield.

From Testapp:
Before:
image
After:
image

=> 71 MB -> 65 MB

**Comment by michaelklishin** [comment]
So an 8.5% improvement. This is certainly meaningful. I will trust your and @stebet's judgment on the need to yield.

**Review by michaelklishin — APPROVED** [review]

**Comment by lukebakken** [comment]
@bollhals actually this has been discussed. Searching this repo for the string `yield` turns up this issue ...

https://github.com/rabbitmq/rabbitmq-dotnet-client/issues/341

...and this PR...

https://github.com/rabbitmq/rabbitmq-dotnet-client/pull/760

I will revert the changes here.

**Comment by lukebakken** [comment]
Reverted by aa5e8cb

**Comment by bollhals** [comment]
> @bollhals actually this has been discussed. Searching this repo for the string `yield` turns up this issue ...
> 
> #341
> 
> ...and this PR...
> 
> #760
> 
> I will revert the changes here. We can't remove the yield until the client is refactored to be async, basically.

I'd like to understand how this pervents the deadlock, but I haven't been able to find a test case to reproduce it. (I'd like to add one if there isn't. So it is clear to everyone why it is needed)
From the comments in #341 I wasn't able to break it, even with [the code provided here](https://gist.github.com/karoberts/bc10a6aa57d9bcfeda10fca86b68ffca).

**Comment by bollhals** [comment]
Now that I think of it, Is it possible that #844 fixed the issue so it isn't needed anymore?

**Comment by lukebakken** [comment]
This is something @danielmarbach and / or @bording should weigh in on if they have time. No hurry at all.

**Comment by danielmarbach** [comment]
I looked at the current implementation on master and I think the changes proposed here should be fine. If I recall correctly (and I doubt that given my bad memories) we basically introduced the yield as a precaution. Around the timeframe when the first version of the code was introduced we didn't really have a good possibility to run continuations async other than doing some nasty reflection tricks, or wrap the task completion source TrySet methods with Task.Run or enforce async continuations by doing the `Task.Yield`. With the current code either using `RunContinuationsAsynchronously` or setting the channels continuation behavior to `AllowSynchronousContinuations = false` this problem should be mitigated I think although I haven't spend a lot of time digging through everything.

**Pull request merged**
