### PR TITLE
Update appveyor.yml to download latest dotnetcore package

### PR DESCRIPTION
**Pull request by kjnilsson**
just want to test the appveyor config first.

### CODE REVIEW

**Comment by bording** [comment]
FYI, it might be worth trying to use
https://raw.githubusercontent.com/dotnet/cli/rel/1.0.0-preview2/scripts/obtain/dotnet-install.ps1
 
instead, as mentioned [here](http://blog.stephencleary.com/2016/06/dotnet-netcore-versions.html)

**Comment by kjnilsson** [comment]
Thanks @bording. I'll look into it. :)

**Comment by kjnilsson** [comment]
Fixes a missed aspect of #213

**Comment by michaelklishin** [comment]
AppVeyor build passed => assuming that's what we want from this PR.

**Pull request merged**
