### PR TITLE
Fix perpetual auto-recovery problem

### PR DESCRIPTION
**Pull request by mot256**
## Proposed Changes

We have found an issue where if a consumer of an auto-delete queue is cancelled, the auto-recovery will fail perpetually. 

After debugging we found that, when a consumer of an auto-delete queue is cancelled, the recording of the queue is removed from the auto-recovery list, but the associated bindings were not removed from the recording. Leading to a perpetual error stating that the binding cannot be done because the queue does not exist.

## Types of Changes

What types of changes does your code introduce to this project?
_Put an `x` in the boxes that apply_

- [x] Bug fix (non-breaking change which fixes issue #NNNN)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause an observable behavior change in existing systems)
- [ ] Documentation improvements (corrections, new content, etc)
- [ ] Cosmetic change (whitespace, formatting, etc)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating
the PR. If you're unsure about any of them, don't hesitate to ask on the
mailing list. We're here to help! This is simply a reminder of what we are
going to look for before merging your code._

- [x] I have read the `CONTRIBUTING.md` document
- [x] I have signed the CA (see https://cla.pivotal.io/sign/rabbitmq)
- [x] All tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in related repositories

## Further Comments

You will also note that I fixed inconsistent locking that could lead to further auto-recovery issues due to _recordedBindings variable not being locked with the same lock while reading and writing.

### CODE REVIEW

**Comment by michaelklishin** [comment]
Your description of the problem and proposed solution make sense.

**Review by michaelklishin — APPROVED** [review]

**Comment by michaelklishin** [comment]
@mot256 thank you. Can you please submit the same change against `main`?

**Comment by michaelklishin** [comment]
I cherry-picked this to `7.x` but `main` uses file-scoped namespaces, so cherry-picking cannot apply cleanly. It may be more practical to submit the same PR for `main`.

**Comment by mot256** [comment]
> @mot256 thank you. Can you please submit the same change against `main`?

Will do. Thanks.

**Comment by mot256** [comment]
@michaelklishin when are you planning to release 3.6.1 that will include this fix? We are having issues in production that are directly linked to this issue.

**Comment by lukebakken** [comment]
I'll get a release done within the next few hours.

**Comment by lukebakken** [comment]
@mot256 - https://www.nuget.org/packages/RabbitMQ.Client/6.3.1

I'm getting the release details sorted out here right now. Thanks again for your contribution.

**Pull request merged**
