### PR TITLE
Update Directory.Build.props

### PR DESCRIPTION
**Pull request by stebet**
## Proposed Changes
Setting "langversion" to latest to prevent usage of .NET Core-only features.

## Types of Changes

- [X] Bug fix (non-breaking change which fixes issue #NNNN)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause an observable behavior change in existing systems)
- [ ] Documentation improvements (corrections, new content, etc)
- [ ] Cosmetic change (whitespace, formatting, etc)

## Checklist

- [X] I have read the `CONTRIBUTING.md` document
- [X] I have signed the CA (see https://cla.pivotal.io/sign/rabbitmq)
- [X] All tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in related repositories

### CODE REVIEW

**Comment by lukebakken** [comment]
Just curious, does this require reverting any of the code cleanup you've done recently?

**Comment by lukebakken** [comment]
Aha, looks like we're getting some useful build failures -

https://ci.appveyor.com/project/rabbitmq/rabbitmq-dotnet-client/builds/30915139

**Comment by stebet** [comment]
Interesting. I'll fix those :)

**Comment by bording** [comment]
Why set it to `latest` vs. just removing `LangVersion` completely?

**Comment by stebet** [comment]
> Why set it to `latest` vs. just removing `LangVersion` completely?
> 
> EDIT: I guess if you're thinking people might still use VS 2017, then there would be a reason to set this to `latest`, but that's already the default in VS 2019.

Main reason mainly to make it easy to experiment later with other language versions. Hardcoding it to 7.3 while .NET Framework is still being targeted.

**Comment by stebet** [comment]
I have fixed the LangVersion issues :)

**Comment by lukebakken** [comment]
@stebet thank you

**Comment by lukebakken** [comment]
@stebet if you don't mind, please update your existing PRs with these changes. Thanks!!

**Comment by stebet** [comment]
Just did :)

**Comment by stebet** [comment]
> @stebet if you don't mind, please update your existing PRs with these changes. Thanks!!

Just did :)

**Pull request merged**
