### PR TITLE
Coding style cleanup for ApiGen

### PR DESCRIPTION
**Pull request by stebet**
## Proposed Changes

The first of probably many PRs for code style/readability updates :)

These are purely cosmetic changes to the ApiGen project to generate code conforming to the .editorconfig settings and increasing readability.

Also adding a Directory.Build.props file to the solution where settings that apply to all projects can be put

Setting the C# lang version to 8.0 to enable new language features.

**There are no changes to the public facing API.**

## Types of Changes

What types of changes does your code introduce to this project?
- [ ] Bug fix (non-breaking change which fixes issue #NNNN)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause an observable behavior change in existing systems)
- [ ] Documentation improvements (corrections, new content, etc)
- [X] Cosmetic change (whitespace, formatting, etc)

## Checklist

- [X] I have read the `CONTRIBUTING.md` document
- [X] I have signed the CA (see https://cla.pivotal.io/sign/rabbitmq)
- [X] All tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in related repositories

### CODE REVIEW

**Comment by michaelklishin** [comment]
Thank you!

**Comment by bording** [comment]
> Setting the C# lang version to 8.0 to enable new language features.

This is a potentially dangerous change. C# 8 is only officially supported with .NET Core 3.x and NET Standard 2.1.

While some language features are fine to use, there are some that require runtime changes, so they can't actually be used on .NET Framework or .NET Core 2.x. That's why Microsoft only enables C# 8 by default when you target `netcoreapp3.1` or `netstandard2.1`.

**Comment by lukebakken** [comment]
Thanks @bording I was going to look into that too. A lot happened while I was sleeping last night 😺

**Comment by stebet** [comment]
Yeah, maybe better to not do that and just set it to "latest" (which uses the latest for that targetframework). Not using any of the Core specific language features though, but I guess it's better to prevent that from happening altogether.

**Comment by stebet** [comment]
Actually, if you try to use a core specific feature in C# 8 you get compilation errors for non standard2.1 or Core framework targets if they aren't supported as far as I can tell. I'll verify.

**Comment by stebet** [comment]
Here is a good explanation on what works and what doesn't: https://stackoverflow.com/a/57020770

**Comment by bording** [comment]
> Yeah, maybe better to not do that and just set it to "latest" (which uses the latest for that targetframework).

If you aren't setting it to a specific version, at this point I think it's better to leave it unset, based on how the automatic selection works based on TFM. https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/configure-language-version

> Actually, if you try to use a core specific feature in C# 8 you get compilation errors for non standard2.1 or Core framework targets if they aren't supported as far as I can tell. I'll verify.

Some things might have compilation errors because the language feature requires types that aren't in the older frameworks, ranges for example.

Default interface members is one place where I don't think there are new types needed, so it would blow up at runtime.

**Comment by stebet** [comment]
According to this the compiler throws an error on unsupported features: https://stu.dev/csharp8-doing-unsupported-things/

**Comment by bording** [comment]
I hadn't tried it myself before, so I just did, and yes there does appear to be a "Target runtime doesn't support default interface implementation" compile error.

**Comment by lukebakken** [comment]
Thanks for investigating everyone. Sounds like the best solution is to not set a specific language version. @stebet would you like to open a new PR with that or I could? I don't want to duplicate work is all. Thanks.

**Comment by stebet** [comment]
I'll do it :)

**Pull request merged**
