### PR TITLE
Expose DispatchConsumersAsync as a readonly from ConnectionFactory to IConnection

### PR DESCRIPTION
**Pull request by luizcarlosfaria**
## Proposed Changes

Expose `DispatchConsumersAsync` property from internal `_config.DispatchConsumersAsync` to a read only property on `IConnection` interface, described in #1610.

Creating a consumer that receive a `IConnection` from dependency injection, without touch on `IConnectionFactory`, understand if connection will use **async** or **sync** dispatch is important to validate and help a developer to configure `ConnectionFactory` right. 

It will enable to create a validation that avoids starting a consumer who never dispatches messages to user code because the connection is defined with synchronous dispatch and consumer is asynchronous or vice versa.

## Types of Changes

Promote a hidden property defined on constructor to expose as a part of IConnection Interface.

- [x] New feature (non-breaking change which adds functionality)

## Checklist

- [X] I have read the `CONTRIBUTING.md` document
- [X] I have signed the CA (see https://cla.pivotal.io/sign/rabbitmq)
- [X] All tests pass locally with my changes
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] I have added necessary documentation (if appropriate)
- [X] Any dependent changes have been merged and published in related repositories

### CODE REVIEW

**Comment by michaelklishin** [comment]
Thank you for taking the time to contribute.

**Comment by lukebakken** [comment]
Hello and thanks for your contribution. Since version 7 should ship "soon", I'm hesitant to accept API changes.

Please note that using the wrong combination of `DispatchConsumersAsync` and a consumer class will throw an exception:

https://github.com/rabbitmq/rabbitmq-dotnet-client/blob/main/projects/RabbitMQ.Client/client/impl/ChannelBase.cs#L976-L982

**Comment by luizcarlosfaria** [comment]
> Hello and thanks for your contribution. Since version 7 should ship "soon", I'm hesitant to accept API changes.
> 
> Please note that using the wrong combination of `DispatchConsumersAsync` and a consumer class will throw an exception:
> 
> https://github.com/rabbitmq/rabbitmq-dotnet-client/blob/main/projects/RabbitMQ.Client/client/impl/ChannelBase.cs#L976-L982

Great news, but instead, must be adding a inverse check to guarantee that if ConsumerDispatcher is Synchronous, throw a exception when consumer is Async. 

In my case, the only implementation of consumer is Async, but sometime, users do not configure ConnectionFactory properly, ignoring DispatchConsumersAsync property (by default is false).

The way to make consistence guarantee is requesting the user ConnectionFactory to do my validations but by design handle the ConnectionFactory is not my business. 

ConnectionFactory and Connection is handled by user code, my job is use a valid connection to create a consumer.

The effect is that consumer never be called.

**Comment by lukebakken** [comment]
Hi @luizcarlosfaria, I didn't realize you're using this library as part of a larger project that could benefit RabbitMQ users everywhere (https://github.com/luizcarlosfaria/Oragon.RabbitMQ).

Let me re-visit this PR. I agree, the validation needs to be consistent.

**Comment by lukebakken** [comment]
I have taken the code in this PR and added to it here - https://github.com/rabbitmq/rabbitmq-dotnet-client/pull/1615

**Pull request closed without merging**
